"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { isKgmAvatarUpload } from "./KgmAvatar";

type GalleryKind = "all" | "image" | "video" | "audio" | "apk";
type MediaKind = Exclude<GalleryKind, "all">;
type Account = { id:string; email:string; nickname:string; role:"Child"|"Teen"|"Adult" };
type UploadItem = { id:string; title:string; description:string; kind:MediaKind; content_type:string; filename:string; size:number; sha256:string; created_at:string; uploader:{id:string;nickname:string;role:string}; file_url:string; download_url:string; report_count?:number };
type Selected = { file:File; kind:MediaKind; previewUrl:string };
type AuthStateDetail = { authenticated:boolean; user?:Account };

const TOKEN_KEY = "kgm-village-chat-token-v2";
const MB = 1024 * 1024;
const LIMITS:Record<MediaKind,number> = { image:10*MB, audio:25*MB, video:500*MB, apk:200*MB };
const KINDS:{id:GalleryKind;label:string;icon:string}[] = [
  {id:"all",label:"Everything",icon:"✦"},{id:"image",label:"Photos",icon:"▧"},{id:"video",label:"Videos",icon:"▶"},{id:"audio",label:"Music",icon:"♪"},{id:"apk",label:"APKs",icon:"⬡"},
];

function bytes(v:number){ if(v<MB)return `${Math.max(1,Math.round(v/1024))} KB`; return `${(v/MB).toFixed(v>10*MB?0:1)} MB`; }
function dateLabel(v:string){ const d=new Date(v); return Number.isNaN(d.getTime())?"Recently":new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(d); }
function detect(file:File):MediaKind{ const t=(file.type||"").toLowerCase(),n=file.name.toLowerCase(); if(t.startsWith("image/"))return"image"; if(t.startsWith("video/")||/\.(mp4|mov|m4v|3gp|3gpp|webm|mpeg|mpg|avi)$/i.test(n))return"video"; if(t.startsWith("audio/")||/\.(mp3|m4a|aac|wav|ogg|opus)$/i.test(n))return"audio"; if(n.endsWith(".apk")||t==="application/vnd.android.package-archive"||t==="application/octet-stream")return"apk"; return"apk"; }
function uniqueUploads(list:UploadItem[]){ const seen=new Set<string>(); return list.filter(item=>{ if(isKgmAvatarUpload(item))return false; const digest=(item.sha256||"").trim().toLowerCase(); const key=digest?`${item.kind}:${digest}`:`id:${item.id}`; if(seen.has(key))return false; seen.add(key); return true; }); }

async function request<T>(url:string,init?:RequestInit,token?:string):Promise<T>{
  const headers=new Headers(init?.headers||{}); if(token)headers.set("Authorization",`Bearer ${token}`); if(init?.body&&!(init.body instanceof FormData))headers.set("Content-Type","application/json");
  let response:Response; try{response=await fetch(url,{...init,headers,cache:"no-store"});}catch{throw new Error(navigator.onLine?"KGM could not reach the gallery. Try again.":"You are offline. Reconnect and try again.");}
  const data=await response.json().catch(()=>({})); if(!response.ok)throw Object.assign(new Error(typeof data?.detail==="string"?data.detail:"Request failed"),{status:response.status}); return data as T;
}

function uploadRequest(url:string,data:FormData,token:string,onProgress:(percent:number)=>void):Promise<UploadItem>{
  return new Promise((resolve,reject)=>{
    const xhr=new XMLHttpRequest(); xhr.open("POST",url,true); xhr.responseType="json"; if(token)xhr.setRequestHeader("Authorization",`Bearer ${token}`);
    xhr.upload.onprogress=(event)=>{if(event.lengthComputable&&event.total>0)onProgress(Math.min(99,Math.round((event.loaded/event.total)*100)));};
    xhr.onload=()=>{const body=xhr.response&&typeof xhr.response==="object"?xhr.response:(()=>{try{return JSON.parse(xhr.responseText||"{}")}catch{return{}}})();if(xhr.status>=200&&xhr.status<300){onProgress(100);resolve(body as UploadItem);return;}const err=Object.assign(new Error(typeof body?.detail==="string"?body.detail:`Upload failed (${xhr.status})`),{status:xhr.status});reject(err);};
    xhr.onerror=()=>reject(new Error(navigator.onLine?"Upload connection was interrupted. Keep KGM open and try again.":"Upload stopped because the phone went offline."));
    xhr.onabort=()=>reject(new Error("Upload was cancelled before it finished."));
    // Intentionally no xhr.timeout: large APK/video uploads on mobile networks can take minutes.
    xhr.send(data);
  });
}

export default function CommunityGalleryV3(){
  const [open,setOpen]=useState(false),[uploadOpen,setUploadOpen]=useState(false),[navHost,setNavHost]=useState<Element|null>(null),[account,setAccount]=useState<Account|null>(null);
  const [items,setItems]=useState<UploadItem[]>([]),[kind,setKind]=useState<GalleryKind>("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[uploadProgress,setUploadProgress]=useState(0),[error,setError]=useState("");
  const [selected,setSelected]=useState<Selected|null>(null),[editing,setEditing]=useState<UploadItem|null>(null),[reported,setReported]=useState<Set<string>>(new Set());

  useEffect(()=>setNavHost(document.querySelector(".nav-links")),[]);
  useEffect(()=>()=>{if(selected?.previewUrl)URL.revokeObjectURL(selected.previewUrl)},[selected]);
  useEffect(()=>{const onAuth=(event:Event)=>{const detail=(event as CustomEvent<AuthStateDetail>).detail;if(detail?.authenticated&&detail.user)setAccount(detail.user);else if(detail&&!detail.authenticated)setAccount(null)};window.addEventListener("kgm-auth-state",onAuth);return()=>window.removeEventListener("kgm-auth-state",onAuth)},[]);

  async function refreshAccount(){const token=localStorage.getItem(TOKEN_KEY)||"";if(!token){setAccount(null);return null}try{const me=await request<Account>("/api/kgm-chat/auth/me",undefined,token);setAccount(me);return me}catch(err){if((err as {status?:number})?.status===401){localStorage.removeItem(TOKEN_KEY);setAccount(null);window.dispatchEvent(new Event("kgm-auth-changed"))}return null}}
  async function load(nextKind=kind,nextQuery=query){setLoading(true);setError("");try{const p=new URLSearchParams({kind:nextKind,limit:"100"});if(nextQuery.trim())p.set("q",nextQuery.trim());const data=await request<{items:UploadItem[]}>(`/api/kgm-uploads?${p}`);setItems(uniqueUploads(data.items||[]))}catch(err){setError(err instanceof Error?err.message:"Could not load village uploads")}finally{setLoading(false)}}
  async function openGallery(){setOpen(true);void refreshAccount();await load()}
  function clearSelected(){const input=document.querySelector<HTMLInputElement>("#kgm-community-upload-file");if(input)input.value="";setSelected(null);setUploadProgress(0)}
  function choose(event:ChangeEvent<HTMLInputElement>){const file=event.currentTarget.files?.[0];if(!file)return clearSelected();const next=detect(file),limit=LIMITS[next];if(file.size>limit){setError(`${next==="video"?"Video":next==="apk"?"APK":"File"} is ${bytes(file.size)}. Maximum is ${bytes(limit)}.`);event.currentTarget.value="";setSelected(null);return}setError("");setSelected({file,kind:next,previewUrl:next==="apk"?"":URL.createObjectURL(file)})}
  function openSignin(){setUploadOpen(false);document.querySelector<HTMLButtonElement>(".village-chat-launcher")?.click()}

  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(uploading)return;const token=localStorage.getItem(TOKEN_KEY)||"";if(!token||!account){setError("Sign in to your KGM account before uploading.");return}const form=event.currentTarget,data=new FormData(form),file=data.get("file");if(!(file instanceof File)||!file.size){setError("Choose a file first.");return}const mediaKind=detect(file);if(file.size>LIMITS[mediaKind]){setError(`${mediaKind==="video"?"Video":mediaKind==="apk"?"APK":"File"} exceeds ${bytes(LIMITS[mediaKind])}.`);return}if(data.get("rights_confirmed")!=="on"){setError("Confirm that you have permission to share this file.");return}setUploading(true);setUploadProgress(1);setError("");try{data.set("rights_confirmed","true");const item=await uploadRequest("/api/kgm-uploads",data,token,setUploadProgress);const duplicate=items.find(x=>x.kind===item.kind&&x.sha256&&item.sha256&&x.sha256.toLowerCase()===item.sha256.toLowerCase());if(duplicate){await request(`/api/kgm-uploads/${item.id}`,{method:"DELETE"},token).catch(()=>undefined);setError("That exact file is already in KGM, so a duplicate was not added.");clearSelected();return}setItems(current=>uniqueUploads([item,...current]));form.reset();clearSelected();setKind("all");setQuery("");setUploadOpen(false);window.dispatchEvent(new Event("kgm-gallery-updated"))}catch(err){if((err as {status?:number})?.status===401){localStorage.removeItem(TOKEN_KEY);setAccount(null);setError("Your KGM session expired. Sign in and try again.")}else setError(err instanceof Error?err.message:"Upload failed")}finally{setUploading(false)}}
  async function saveEdit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const token=localStorage.getItem(TOKEN_KEY)||"",data=new FormData(event.currentTarget);try{const updated=await request<UploadItem>(`/api/kgm-uploads/${editing.id}`,{method:"PUT",body:JSON.stringify({title:String(data.get("title")||"").trim(),description:String(data.get("description")||"").trim()})},token);setItems(current=>current.map(x=>x.id===updated.id?updated:x));setEditing(null)}catch(err){setError(err instanceof Error?err.message:"Could not save changes")}}
  async function remove(item:UploadItem){const token=localStorage.getItem(TOKEN_KEY)||"";try{await request(`/api/kgm-uploads/${item.id}`,{method:"DELETE"},token);setItems(current=>current.filter(x=>x.id!==item.id))}catch(err){setError(err instanceof Error?err.message:"Could not delete upload")}}
  async function report(item:UploadItem){const token=localStorage.getItem(TOKEN_KEY)||"";if(!token){setError("Sign in before reporting an upload.");return}try{const result=await request<{hidden?:boolean}>(`/api/kgm-uploads/${item.id}/report`,{method:"POST",body:JSON.stringify({reason:"Reported from KGM public gallery"})},token);setReported(current=>new Set(current).add(item.id));if(result.hidden)setItems(current=>current.filter(x=>x.id!==item.id))}catch(err){setError(err instanceof Error?err.message:"Could not report upload")}}

  const counts=useMemo(()=>items.reduce<Record<string,number>>((acc,item)=>(acc[item.kind]=(acc[item.kind]||0)+1,acc),{}),[items]);
  const nav=navHost?createPortal(<button className="kgm-gallery-nav-link" type="button" onClick={openGallery}>Gallery</button>,navHost):null;

  return <>{nav}{open&&<div className="kgm-gallery-backdrop" role="dialog" aria-modal="true"><section className="kgm-gallery-shell">
    <header className="kgm-gallery-head"><div><span>KGM COMMUNITY · మన ఊరి గ్యాలరీ</span><h2>Made here. Shared with everyone.</h2><p>Photos, village videos, songs and community APKs from KGM creators.</p></div><div className="kgm-gallery-head-actions"><button className="kgm-gallery-upload-button" onClick={async()=>{await refreshAccount();clearSelected();setError("");setUploadOpen(true)}}>＋ Upload</button><button className="kgm-gallery-close" onClick={()=>setOpen(false)}>×</button></div></header>
    <div className="kgm-gallery-toolbar"><div className="kgm-gallery-tabs">{KINDS.map(entry=><button key={entry.id} className={kind===entry.id?"active":""} onClick={async()=>{setKind(entry.id);await load(entry.id,query)}}><span>{entry.icon}</span>{entry.label}{entry.id!=="all"&&counts[entry.id]?<b>{counts[entry.id]}</b>:null}</button>)}</div><form onSubmit={async event=>{event.preventDefault();await load(kind,query)}}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search village uploads…"/><button>Search</button></form></div>
    <div className="kgm-gallery-public-note"><span>🌍</span><p><strong>Public by design.</strong> Anyone can browse these uploads. Uploading, editing, deleting and reporting use a KGM account. <a href="/privacy">Privacy & safety</a></p></div>{error&&!uploadOpen&&<p className="kgm-gallery-error">{error}</p>}
    <div className="kgm-gallery-grid">{loading&&<div className="kgm-gallery-empty"><span>◌</span><strong>Loading village uploads…</strong></div>}{!loading&&!items.length&&<div className="kgm-gallery-empty"><span>✦</span><strong>No uploads here yet.</strong><p>The next drop starts with you.</p></div>}{!loading&&items.map(item=><article className={`kgm-upload-card ${item.kind}`} key={item.id}><div className="kgm-upload-media">{item.kind==="image"&&<img src={item.file_url} alt={item.title} loading="lazy"/>}{item.kind==="video"&&<video src={item.file_url} controls preload="metadata" playsInline/>}{item.kind==="audio"&&<div className="kgm-audio-art"><span>♪</span><strong>{item.title}</strong><small>{item.uploader.nickname}</small><audio src={item.file_url} controls preload="metadata"/></div>}{item.kind==="apk"&&<div className="kgm-apk-art"><span>APK</span><strong>{item.title}</strong><small>Unverified community app</small></div>}</div><div className="kgm-upload-body"><div className="kgm-upload-kind"><span>{item.kind==="audio"?"MUSIC":item.kind.toUpperCase()}</span><b>{bytes(item.size)}</b></div><h3>{item.title}</h3>{item.description&&<p>{item.description}</p>}<div className="kgm-upload-by"><span>{item.uploader.nickname.slice(0,1).toUpperCase()}</span><div><strong>{item.uploader.nickname}</strong><small>{item.uploader.role} · {dateLabel(item.created_at)}</small></div></div><div className={`kgm-upload-actions ${account?.id===item.uploader.id?"owner-actions":""}`}><a href={item.download_url} download>{item.kind==="apk"?"Download APK":"Save file"}</a>{account?.id===item.uploader.id?<><button className="kgm-edit-upload" onClick={()=>setEditing(item)}>Edit</button><button className="kgm-delete-upload" onClick={()=>remove(item)}>Delete</button></>:<button disabled={reported.has(item.id)} onClick={()=>report(item)}>{reported.has(item.id)?"Reported ✓":"Report"}</button>}</div></div></article>)}</div>
  </section>
  {uploadOpen&&<div className="kgm-upload-modal-backdrop"><form className="kgm-upload-modal" onSubmit={upload}><header><div><span>SHARE WITH KORATLAGUDEM</span><h3>Upload to the public gallery</h3></div><button type="button" disabled={uploading} onClick={()=>{clearSelected();setUploadOpen(false)}}>×</button></header>{account?<div className="kgm-upload-account"><span>{account.nickname.slice(0,1).toUpperCase()}</span><p>Posting as <strong>{account.nickname}</strong> · {account.role}</p></div>:<div className="kgm-upload-signin"><strong>Sign in needed.</strong><p>Sign in or create your KGM account, then return here.</p><button type="button" onClick={openSignin}>Sign in / Create account →</button></div>}{error&&<p className="kgm-gallery-error">{error}</p>}<label>Title<input name="title" required maxLength={100} disabled={!account||uploading}/></label><label>Description<textarea name="description" maxLength={500} rows={3} disabled={!account||uploading}/></label><label className="kgm-upload-file">Choose photo, song, video or APK<input id="kgm-community-upload-file" name="file" type="file" required disabled={!account||uploading} accept="image/*,video/*,audio/*,.apk,application/vnd.android.package-archive,application/octet-stream" onChange={choose}/><small>Images ≤10 MB · music ≤25 MB · videos ≤500 MB · APKs ≤200 MB.</small></label>{selected&&<div className={`kgm-upload-selection ${selected.kind}`}><div className="kgm-upload-selection-head"><div><span>SELECTED {selected.kind.toUpperCase()}</span><strong>{selected.file.name}</strong><small>{bytes(selected.file.size)}</small></div><button type="button" disabled={uploading} onClick={clearSelected}>Change</button></div>{selected.kind==="image"&&<img src={selected.previewUrl} alt="Selected preview"/>}{selected.kind==="video"&&<video src={selected.previewUrl} controls playsInline preload="metadata"/>}{selected.kind==="audio"&&<audio src={selected.previewUrl} controls/>}</div>}<label className="kgm-upload-rights"><input name="rights_confirmed" type="checkbox" required disabled={!account||uploading}/><span>I own this file or have permission to share it publicly.</span></label><div className="kgm-upload-policy"><strong>Public upload</strong><p>Exact duplicate files are automatically blocked. <a href="/privacy">Read KGM Privacy & Safety.</a></p></div>{uploading&&<div className="kgm-upload-progress" role="status" aria-live="polite"><strong>Uploading… {uploadProgress}%</strong><progress value={uploadProgress} max={100}/><small>Keep this page open until the upload finishes.</small></div>}<button className="kgm-upload-submit" type="submit" disabled={!account||uploading||!selected}>{uploading?`Uploading ${uploadProgress}%…`:selected?`Publish ${selected.kind} for everyone →`:"Choose a file to continue"}</button></form></div>}
  {editing&&<div className="kgm-upload-modal-backdrop kgm-edit-modal-backdrop"><form className="kgm-upload-modal kgm-edit-modal" onSubmit={saveEdit}><header><div><span>YOUR UPLOAD</span><h3>Edit details</h3></div><button type="button" onClick={()=>setEditing(null)}>×</button></header><label>Title<input name="title" defaultValue={editing.title} required maxLength={100}/></label><label>Description<textarea name="description" defaultValue={editing.description} maxLength={500} rows={4}/></label><div className="kgm-edit-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="kgm-edit-save" type="submit">Save changes →</button></div></form></div>}
  </div>}</>;
}
