"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { isKgmAvatarUpload } from "./KgmAvatar";

type GalleryKind = "all" | "image" | "video" | "audio" | "apk";
type MediaKind = Exclude<GalleryKind, "all">;
type Account = { id: string; email: string; nickname: string; role: "Child" | "Teen" | "Adult" };
type UploadItem = { id:string; title:string; description:string; kind:MediaKind; content_type:string; filename:string; size:number; sha256:string; created_at:string; uploader:{id:string;nickname:string;role:string}; file_url:string; download_url:string; report_count?:number };
type Selected = { file:File; kind:MediaKind; previewUrl:string };
type AuthStateDetail = { authenticated:boolean; user?:Account };

const TOKEN_KEY = "kgm-village-chat-token-v2";
const MB = 1024 * 1024;
const LIMITS: Record<MediaKind, number> = { image:10*MB, audio:25*MB, video:500*MB, apk:200*MB };
const KINDS:{id:GalleryKind;label:string;icon:string}[] = [
  {id:"all",label:"Everything",icon:"✦"},{id:"image",label:"Photos",icon:"▧"},{id:"video",label:"Videos",icon:"▶"},{id:"audio",label:"Music",icon:"♪"},{id:"apk",label:"APKs",icon:"⬡"},
];

function bytes(value:number){ if(value<MB) return `${Math.max(1,Math.round(value/1024))} KB`; return `${(value/MB).toFixed(value>10*MB?0:1)} MB`; }
function dateLabel(value:string){ const d=new Date(value); return Number.isNaN(d.getTime())?"Recently":new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(d); }
function detect(file:File):MediaKind{ const t=(file.type||"").toLowerCase(),n=file.name.toLowerCase(); if(t.startsWith("image/"))return"image"; if(t.startsWith("video/")||/\.(mp4|mov|m4v|3gp|3gpp|webm|mpeg|mpg|avi)$/i.test(n))return"video"; if(t.startsWith("audio/")||/\.(mp3|m4a|aac|wav|ogg|opus)$/i.test(n))return"audio"; return"apk"; }
async function request<T>(url:string,init?:RequestInit,token?:string):Promise<T>{ const h=new Headers(init?.headers||{}); if(token)h.set("Authorization",`Bearer ${token}`); if(init?.body&&!(init.body instanceof FormData))h.set("Content-Type","application/json"); const controller=new AbortController(); const timer=window.setTimeout(()=>controller.abort(),30000); try{ const r=await fetch(url,{...init,headers:h,cache:"no-store",signal:controller.signal}); const data=await r.json().catch(()=>({})); if(!r.ok)throw Object.assign(new Error(typeof data?.detail==="string"?data.detail:"Request failed"),{status:r.status}); return data as T; }finally{window.clearTimeout(timer);} }

export default function CommunityGalleryV2(){
  const [open,setOpen]=useState(false),[uploadOpen,setUploadOpen]=useState(false);
  const [navHost,setNavHost]=useState<Element|null>(null),[account,setAccount]=useState<Account|null>(null);
  const [items,setItems]=useState<UploadItem[]>([]),[kind,setKind]=useState<GalleryKind>("all"),[query,setQuery]=useState("");
  const [loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState("");
  const [selected,setSelected]=useState<Selected|null>(null),[editing,setEditing]=useState<UploadItem|null>(null),[reported,setReported]=useState<Set<string>>(new Set());

  useEffect(()=>setNavHost(document.querySelector(".nav-links")),[]);
  useEffect(()=>()=>{if(selected?.previewUrl)URL.revokeObjectURL(selected.previewUrl)},[selected]);
  useEffect(()=>{ const onAuth=(event:Event)=>{const detail=(event as CustomEvent<AuthStateDetail>).detail;if(detail?.authenticated&&detail.user)setAccount(detail.user);else if(detail&&!detail.authenticated)setAccount(null);}; window.addEventListener("kgm-auth-state",onAuth); return()=>window.removeEventListener("kgm-auth-state",onAuth);},[]);

  async function refreshAccount(){ const token=localStorage.getItem(TOKEN_KEY)||""; if(!token){setAccount(null);return null;} try{const me=await request<Account>("/api/kgm-chat/auth/me",undefined,token);setAccount(me);return me;}catch(err){if((err as {status?:number})?.status===401){localStorage.removeItem(TOKEN_KEY);setAccount(null);window.dispatchEvent(new Event("kgm-auth-changed"));}return null;} }
  async function load(nextKind=kind,nextQuery=query){setLoading(true);setError("");try{const p=new URLSearchParams({kind:nextKind,limit:"100"});if(nextQuery.trim())p.set("q",nextQuery.trim());const data=await request<{items:UploadItem[]}>(`/api/kgm-uploads?${p}`);setItems((data.items||[]).filter(i=>!isKgmAvatarUpload(i)));}catch(err){setError(err instanceof Error?err.message:"Could not load village uploads");}finally{setLoading(false);} }
  async function openGallery(){setOpen(true);await Promise.all([refreshAccount(),load()]);}
  function clearSelected(){const el=document.querySelector<HTMLInputElement>("#kgm-community-upload-file");if(el)el.value="";setSelected(null);}
  function choose(event:ChangeEvent<HTMLInputElement>){const file=event.currentTarget.files?.[0];if(!file)return clearSelected();const next=detect(file),limit=LIMITS[next];if(file.size>limit){setError(`${next==="video"?"Video":next==="apk"?"APK":"File"} is ${bytes(file.size)}. Maximum is ${bytes(limit)}.`);event.currentTarget.value="";return setSelected(null);}setError("");setSelected({file,kind:next,previewUrl:next==="apk"?"":URL.createObjectURL(file)});}
  function openSignin(){setUploadOpen(false);document.querySelector<HTMLButtonElement>(".village-chat-launcher")?.click();}

  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(uploading)return;const token=localStorage.getItem(TOKEN_KEY)||"";if(!token||!account){setError("Your KGM session needs sign-in before uploading.");return;}const form=event.currentTarget,data=new FormData(form),file=data.get("file");if(!(file instanceof File)||!file.size)return setError("Choose a file first.");const mediaKind=detect(file);if(file.size>LIMITS[mediaKind])return setError(`${mediaKind==="video"?"Video":mediaKind==="apk"?"APK":"File"} exceeds ${bytes(LIMITS[mediaKind])}.`);if(data.get("rights_confirmed")!=="on")return setError("Confirm that you have permission to share this file.");setUploading(true);setError("");try{data.set("rights_confirmed","true");const item=await request<UploadItem>("/api/kgm-uploads",{method:"POST",body:data},token);setItems(c=>[item,...c.filter(x=>x.id!==item.id)]);form.reset();clearSelected();setKind("all");setQuery("");setUploadOpen(false);window.dispatchEvent(new Event("kgm-gallery-updated"));}catch(err){if((err as {status?:number})?.status===401){localStorage.removeItem(TOKEN_KEY);setAccount(null);setError("Your previous KGM session expired after the backend move. Sign in once, then upload again.");}else setError(err instanceof Error?err.message:"Upload failed");}finally{setUploading(false);} }
  async function saveEdit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const token=localStorage.getItem(TOKEN_KEY)||"",d=new FormData(event.currentTarget);try{const updated=await request<UploadItem>(`/api/kgm-uploads/${editing.id}`,{method:"PUT",body:JSON.stringify({title:String(d.get("title")||"").trim(),description:String(d.get("description")||"").trim()})},token);setItems(c=>c.map(x=>x.id===updated.id?updated:x));setEditing(null);}catch(err){setError(err instanceof Error?err.message:"Could not save changes");}}
  async function remove(item:UploadItem){const token=localStorage.getItem(TOKEN_KEY)||"";try{await request(`/api/kgm-uploads/${item.id}`,{method:"DELETE"},token);setItems(c=>c.filter(x=>x.id!==item.id));}catch(err){setError(err instanceof Error?err.message:"Could not delete upload");}}
  async function report(item:UploadItem){const token=localStorage.getItem(TOKEN_KEY)||"";if(!token)return setError("Sign in before reporting an upload.");try{const r=await request<{hidden?:boolean}>(`/api/kgm-uploads/${item.id}/report`,{method:"POST",body:JSON.stringify({reason:"Reported from KGM public gallery"})},token);setReported(c=>new Set(c).add(item.id));if(r.hidden)setItems(c=>c.filter(x=>x.id!==item.id));}catch(err){setError(err instanceof Error?err.message:"Could not report upload");}}
  const counts=useMemo(()=>items.reduce<Record<string,number>>((a,i)=>(a[i.kind]=(a[i.kind]||0)+1,a),{}),[items]);
  const nav=navHost?createPortal(<button className="kgm-gallery-nav-link" type="button" onClick={openGallery}>Gallery</button>,navHost):null;

  return <>{nav}{open&&<div className="kgm-gallery-backdrop" role="dialog" aria-modal="true"><section className="kgm-gallery-shell">
    <header className="kgm-gallery-head"><div><span>KGM COMMUNITY · మన ఊరి గ్యాలరీ</span><h2>Made here. Shared with everyone.</h2><p>Photos, village videos, songs and community APKs from KGM creators.</p></div><div className="kgm-gallery-head-actions"><button className="kgm-gallery-upload-button" onClick={async()=>{await refreshAccount();clearSelected();setUploadOpen(true)}}>＋ Upload</button><button className="kgm-gallery-close" onClick={()=>setOpen(false)}>×</button></div></header>
    <div className="kgm-gallery-toolbar"><div className="kgm-gallery-tabs">{KINDS.map(k=><button key={k.id} className={kind===k.id?"active":""} onClick={async()=>{setKind(k.id);await load(k.id,query)}}><span>{k.icon}</span>{k.label}{k.id!=="all"&&counts[k.id]?<b>{counts[k.id]}</b>:null}</button>)}</div><form onSubmit={async e=>{e.preventDefault();await load(kind,query)}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search village uploads…"/><button>Search</button></form></div>
    <div className="kgm-gallery-public-note"><span>🌍</span><p><strong>Public by design.</strong> Anyone can browse these uploads. Uploading, editing, deleting and reporting use a KGM account. <a href="/privacy">Privacy & safety</a></p></div>{error&&<p className="kgm-gallery-error">{error}</p>}
    <div className="kgm-gallery-grid">{loading&&<div className="kgm-gallery-empty"><span>◌</span><strong>Loading village uploads…</strong></div>}{!loading&&!items.length&&<div className="kgm-gallery-empty"><span>✦</span><strong>No uploads here yet.</strong><p>The next drop starts with you.</p></div>}{!loading&&items.map(item=><article className={`kgm-upload-card ${item.kind}`} key={item.id}><div className="kgm-upload-media">{item.kind==="image"&&<img src={item.file_url} alt={item.title} loading="lazy"/>}{item.kind==="video"&&<video src={item.file_url} controls preload="metadata" playsInline/>}{item.kind==="audio"&&<div className="kgm-audio-art"><span>♪</span><strong>{item.title}</strong><small>{item.uploader.nickname}</small><audio src={item.file_url} controls preload="metadata"/></div>}{item.kind==="apk"&&<div className="kgm-apk-art"><span>APK</span><strong>{item.title}</strong><small>Unverified community app</small></div>}</div><div className="kgm-upload-body"><div className="kgm-upload-kind"><span>{item.kind==="audio"?"MUSIC":item.kind.toUpperCase()}</span><b>{bytes(item.size)}</b></div><h3>{item.title}</h3>{item.description&&<p>{item.description}</p>}<div className="kgm-upload-by"><span>{item.uploader.nickname.slice(0,1).toUpperCase()}</span><div><strong>{item.uploader.nickname}</strong><small>{item.uploader.role} · {dateLabel(item.created_at)}</small></div></div><div className={`kgm-upload-actions ${account?.id===item.uploader.id?"owner-actions":""}`}><a href={item.download_url} download>{item.kind==="apk"?"Download APK":"Save file"}</a>{account?.id===item.uploader.id?<><button className="kgm-edit-upload" onClick={()=>setEditing(item)}>Edit</button><button className="kgm-delete-upload" onClick={()=>remove(item)}>Delete</button></>:<button disabled={reported.has(item.id)} onClick={()=>report(item)}>{reported.has(item.id)?"Reported ✓":"Report"}</button>}</div></div></article>)}</div>
  </section>
  {uploadOpen&&<div className="kgm-upload-modal-backdrop"><form className="kgm-upload-modal" onSubmit={upload}><header><div><span>SHARE WITH KORATLAGUDEM</span><h3>Upload to the public gallery</h3></div><button type="button" onClick={()=>{clearSelected();setUploadOpen(false)}}>×</button></header>{account?<div className="kgm-upload-account"><span>{account.nickname.slice(0,1).toUpperCase()}</span><p>Posting as <strong>{account.nickname}</strong> · {account.role}</p></div>:<div className="kgm-upload-signin"><strong>One-time sign-in needed.</strong><p>KGM now has its own backend. Sign in or create your KGM account once, then return here.</p><button type="button" onClick={openSignin}>Sign in / Create account →</button></div>}<label>Title<input name="title" required maxLength={100} disabled={!account}/></label><label>Description<textarea name="description" maxLength={500} rows={3} disabled={!account}/></label><label className="kgm-upload-file">Choose photo, song, video or APK<input id="kgm-community-upload-file" name="file" type="file" required disabled={!account} accept="image/*,video/*,audio/*,.apk,application/vnd.android.package-archive" onChange={choose}/><small>Images ≤10 MB · music ≤25 MB · videos ≤500 MB · APKs ≤200 MB.</small></label>{selected&&<div className={`kgm-upload-selection ${selected.kind}`}><div className="kgm-upload-selection-head"><div><span>SELECTED {selected.kind.toUpperCase()}</span><strong>{selected.file.name}</strong><small>{bytes(selected.file.size)}</small></div><button type="button" onClick={clearSelected}>Change</button></div>{selected.kind==="image"&&<img src={selected.previewUrl} alt="Selected preview"/>}{selected.kind==="video"&&<video src={selected.previewUrl} controls playsInline preload="metadata"/>}{selected.kind==="audio"&&<audio src={selected.previewUrl} controls/>}</div>}<label className="kgm-upload-rights"><input name="rights_confirmed" type="checkbox" required disabled={!account}/><span>I own this file or have permission to share it publicly.</span></label><div className="kgm-upload-policy"><strong>Public upload</strong><p>Your nickname, role and upload can be visible to everyone. <a href="/privacy">Read KGM Privacy & Safety.</a></p></div><button className="kgm-upload-submit" type="submit" disabled={!account||uploading||!selected}>{uploading?"Uploading…":selected?`Publish ${selected.kind} for everyone →`:"Choose a file to continue"}</button></form></div>}
  {editing&&<div className="kgm-upload-modal-backdrop kgm-edit-modal-backdrop"><form className="kgm-upload-modal kgm-edit-modal" onSubmit={saveEdit}><header><div><span>YOUR UPLOAD</span><h3>Edit details</h3></div><button type="button" onClick={()=>setEditing(null)}>×</button></header><label>Title<input name="title" defaultValue={editing.title} required maxLength={100}/></label><label>Description<textarea name="description" defaultValue={editing.description} maxLength={500} rows={4}/></label><div className="kgm-edit-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="kgm-edit-save">Save changes →</button></div></form></div>}
  </div>}</>;
}
