export type KgmLanguage = "en" | "te";

export const KGM_TE: Record<string, string> = {
  "YOUTHVERSE": "యూత్‌వర్స్",
  "LIVE": "ప్రత్యక్షం",
  "Discover": "అన్వేషించండి",
  "Apps": "యాప్స్",
  "Music": "సంగీతం",
  "Cinema": "సినిమా",
  "Gallery": "గ్యాలరీ",
  "Chat": "చాట్",
  "Home": "హోమ్",
  "Upload": "అప్‌లోడ్",
  "Me": "నేను",
  "Profile": "ప్రొఫైల్",
  "Safety": "భద్రత",
  "Young creators": "యువ సృష్టికర్తలు",
  "Sign in": "సైన్ ఇన్",
  "Sign out": "సైన్ అవుట్",
  "Log out": "లాగ్ అవుట్",
  "Sign in / Register": "సైన్ ఇన్ / నమోదు",
  "Create account": "ఖాతా సృష్టించండి",
  "Email": "ఈమెయిల్",
  "Password": "పాస్‌వర్డ్",
  "Public nickname": "పబ్లిక్ పేరు",
  "Child": "పిల్లవాడు/పిల్ల",
  "Teen": "యువకుడు/యువతి",
  "Adult": "పెద్దవారు",
  "All": "అన్నీ",
  "Everything": "అన్నీ",
  "Photos": "ఫోటోలు",
  "Videos": "వీడియోలు",
  "APKs": "APKలు",
  "Photo": "ఫోటో",
  "Video": "వీడియో",
  "Image": "చిత్రం",
  "Audio": "ఆడియో",
  "Search": "వెతకండి",
  "Edit": "సవరించండి",
  "Delete": "తొలగించండి",
  "Cancel": "రద్దు",
  "Change": "మార్చండి",
  "Save file": "ఫైల్ సేవ్ చేయండి",
  "Save changes": "మార్పులు సేవ్ చేయండి",
  "Report": "ఫిర్యాదు",
  "Reported ✓": "ఫిర్యాదు చేయబడింది ✓",
  "Send": "పంపండి",
  "Try again": "మళ్లీ ప్రయత్నించండి",
  "Open Gallery": "గ్యాలరీ తెరవండి",
  "Open full Gallery →": "పూర్తి గ్యాలరీ తెరవండి →",
  "Open Gallery →": "గ్యాలరీ తెరవండి →",
  "See everything in Gallery →": "గ్యాలరీలో అన్నీ చూడండి →",
  "Download APK": "APK డౌన్‌లోడ్ చేయండి",
  "Download": "డౌన్‌లోడ్",
  "Recently": "ఇటీవల",
  "English": "ఆంగ్లం",
  "Telugu": "తెలుగు",
  "English / Folk": "ఆంగ్లం / జానపదం",
  "All ages": "అన్ని వయసులకు",
  "STEM film": "STEM చిత్రం",

  "KGM · VILLAGE-BORN · WORLD-BOUND": "KGM · మన ఊరి నుంచి ప్రపంచానికి",
  "Knowledge should be free for everyone.": "జ్ఞానం అందరికీ ఉచితంగా ఉండాలి.",
  "KGM° · KORATLAGUDEM'S DIGITAL PLAYGROUND": "KGM° · కొరట్లగూడెం డిజిటల్ ఆటస్థలం",
  "KORATLAGUDEM IS CREATING": "కొరట్లగూడెం సృష్టిస్తోంది",
  "MADE HERE.": "ఇక్కడే సృష్టించాం.",
  "SHARED EVERYWHERE.": "ప్రపంచంతో పంచుకుంటాం.",
  "Apps, science, music and creations from Koratlagudem — made locally, open to everyone.": "యాప్స్, సైన్స్, సంగీతం, సృష్టులు — కొరట్లగూడెం నుంచి అందరికీ తెరిచి ఉన్న ప్రపంచానికి.",
  "Explore what's new": "కొత్తవి చూడండి",
  "HAPPENING IN KGM": "KGMలో జరుగుతున్నవి",
  "See what the village is making.": "మన ఊరు ఏమి సృష్టిస్తుందో చూడండి.",
  "Swipe to explore →": "చూడటానికి స్వైప్ చేయండి →",
  "NEW APP": "కొత్త యాప్",
  "NEW MUSIC": "కొత్త సంగీతం",
  "NEW VIDEO": "కొత్త వీడియో",
  "COMMUNITY DROP": "సముదాయం నుంచి కొత్తది",
  "Open →": "తెరవండి →",
  "SCIENCE CINEMA": "సైన్స్ సినిమా",
  "Films that make curiosity bigger.": "జిజ్ఞాసను మరింత పెంచే సినిమాలు.",
  "STEM films · free inside KGM": "STEM సినిమాలు · KGMలో ఉచితం",
  "Watch →": "చూడండి →",
  "COMMUNITY": "సముదాయం",
  "Photos, videos, music and village creations.": "ఫోటోలు, వీడియోలు, సంగీతం, మన ఊరి సృష్టులు.",
  "Fresh from KGM creators": "KGM సృష్టికర్తల నుంచి కొత్తవి",
  "Explore →": "అన్వేషించండి →",
  "DISCOVER": "అన్వేషించండి",
  "One place for every kind of curiosity.": "ప్రతి జిజ్ఞాసకూ ఒకే చోటు.",
  "🛡 Community moderated": "🛡 సముదాయం పర్యవేక్షణలో",
  "STEM ONLY · FREE": "STEM మాత్రమే · ఉచితం",
  "KGM Science Cinema": "KGM సైన్స్ సినిమా",
  "Space, physics, biology, Earth, engineering and more—watch inside KGM.": "అంతరిక్షం, భౌతిక శాస్త్రం, జీవశాస్త్రం, భూమి, ఇంజినీరింగ్ ఇంకా మరెన్నో — KGMలో చూడండి.",
  "START WATCHING ▶": "చూడటం ప్రారంభించండి ▶",
  "PHOTO + VIDEO": "ఫోటో + వీడియో",
  "Village moments deserve a feed, not a folder.": "మన ఊరి క్షణాలు ఫోల్డర్‌లో కాదు, అందరికీ కనిపించే ఫీడ్‌లో ఉండాలి.",
  "See the newest visual drops from KGM creators.": "KGM సృష్టికర్తల తాజా ఫోటోలు, వీడియోలు చూడండి.",
  "OPEN GALLERY ↗": "గ్యాలరీ తెరవండి ↗",
  "NOW PLAYING": "ఇప్పుడు వినిపిస్తోంది",
  "KGM Folk Radio": "KGM జానపద రేడియో",
  "Keep listening while you explore.": "అన్వేషిస్తూ వినడం కొనసాగించండి.",
  "PLAY MUSIC ♪": "సంగీతం వినండి ♪",
  "BUILT HERE": "ఇక్కడే నిర్మించాం",
  "Apps by young makers": "యువ సృష్టికర్తల యాప్స్",
  "From ideas to APKs.": "ఆలోచనల నుంచి APKల వరకు.",
  "EXPLORE APPS ↗": "యాప్స్ చూడండి ↗",
  "LIVE COMMUNITY": "ప్రత్యక్ష సముదాయం",
  "Village Chat": "గ్రామ చాట్",
  "Share ideas without sharing private contact details.": "వ్యక్తిగత సంప్రదింపు వివరాలు పంచుకోకుండా ఆలోచనలు పంచుకోండి.",
  "JOIN CHAT 💬": "చాట్‌లో చేరండి 💬",
  "BUILT BY OUR VILLAGE": "మన ఊరు నిర్మించింది",
  "People are the platform.": "మనుషులే మన వేదిక.",
  "FOUNDING CREW": "ప్రారంభ బృందం",
  "Co-Founder": "సహ వ్యవస్థాపకుడు",
  "Community builder": "సముదాయం నిర్మాణకర్త",
  "Creator energy": "సృజనాత్మక శక్తి",
  "Young maker": "యువ సృష్టికర్త",
  "FOUNDING MEMBER": "ప్రారంభ సభ్యుడు",
  "YOUR TURN": "ఇప్పుడు మీ వంతు",
  "Style your KGM profile": "మీ KGM ప్రొఫైల్‌ను అలంకరించండి",
  "Join the creator wall": "సృష్టికర్తల గోడలో చేరండి",
  "avatar · nickname · role": "అవతార్ · పేరు · పాత్ర",
  "Sign in · upload · build": "సైన్ ఇన్ · అప్‌లోడ్ · నిర్మించండి",
  "EDIT ↗": "సవరించండి ↗",
  "START ↗": "ప్రారంభించండి ↗",

  "LIVE FROM KORATLAGUDEM": "కొరట్లగూడెం నుంచి ప్రత్యక్షం",
  "KGM° · YOUTHVERSE": "KGM° · యూత్‌వర్స్",
  "ORIGIN · 17.12°N 80.02°E": "ఆరంభం · 17.12°N 80.02°E",
  "KORATLAGUDEM": "కొరట్లగూడెం",
  "TELANGANA · INDIA": "తెలంగాణ · భారతదేశం",
  "KORATLAGUDEM YOUTHVERSE": "కొరట్లగూడెం యూత్‌వర్స్",
  "OPEN ACCESS · GLOBAL": "తెరచిన ప్రవేశం · ప్రపంచవ్యాప్తంగా",
  "EVERYWHERE": "ప్రపంచమంతా",
  "Ideas travel farther than their postcode.": "ఆలోచనలకు సరిహద్దులు ఉండవు.",
  "MADE HERE": "ఇక్కడే సృష్టించాం",
  "AMPLIFIED BY KGM": "KGMతో మరింత దూరం",
  "SHARED OUT": "ప్రపంచంతో పంచాం",
  "BUILD": "నిర్మించండి",
  "WATCH": "చూడండి",
  "LISTEN": "వినండి",
  "SHARE": "పంచుకోండి",
  "COMMUNITY NETWORK ONLINE": "సముదాయ నెట్‌వర్క్ ఆన్‌లైన్‌లో ఉంది",
  "LOCAL CREATION → GLOBAL REACH": "మన ఊరి సృష్టి → ప్రపంచ వ్యాప్తి",

  "KGM COMMUNITY · మన ఊరి గ్యాలరీ": "KGM సముదాయం · మన ఊరి గ్యాలరీ",
  "Made here. Shared with everyone.": "ఇక్కడే సృష్టించాం. అందరితో పంచుకున్నాం.",
  "Photos, village videos, songs and community APKs uploaded by KGM members.": "KGM సభ్యులు పంచుకున్న ఫోటోలు, ఊరి వీడియోలు, పాటలు, సముదాయం APKలు.",
  "＋ Upload": "＋ అప్‌లోడ్",
  "Search village uploads…": "మన ఊరి అప్‌లోడ్లలో వెతకండి…",
  "Public by design.": "అందరికీ తెరిచి ఉండేలా రూపొందించాం.",
  "Anyone can browse and enjoy these uploads without signing in. Uploading, editing, deleting and reporting use KGM accounts.": "సైన్ ఇన్ లేకుండానే ఎవరైనా ఈ అప్‌లోడ్లను చూడవచ్చు. అప్‌లోడ్, సవరణ, తొలగింపు, ఫిర్యాదు కోసం KGM ఖాతా అవసరం.",
  "Loading village uploads…": "మన ఊరి అప్‌లోడ్లు లోడ్ అవుతున్నాయి…",
  "No uploads here yet.": "ఇక్కడ ఇంకా అప్‌లోడ్లు లేవు.",
  "Be the first KGM member to share something useful, creative or fun.": "ఉపయోగకరమైనది, సృజనాత్మకమైనది లేదా సరదాగా ఉండేదాన్ని మొదటగా పంచుకోండి.",
  "SHARE WITH KORATLAGUDEM": "కొరట్లగూడెంతో పంచుకోండి",
  "Upload to the public gallery": "పబ్లిక్ గ్యాలరీకి అప్‌లోడ్ చేయండి",
  "Sign in first.": "ముందుగా సైన్ ఇన్ చేయండి.",
  "Use the Sign in button in the KGM navigation, then come back to upload.": "KGM నావిగేషన్‌లో సైన్ ఇన్ చేసి, తర్వాత అప్‌లోడ్‌కు తిరిగి రండి.",
  "Title": "శీర్షిక",
  "Description": "వివరణ",
  "Choose photo, song, video or APK": "ఫోటో, పాట, వీడియో లేదా APK ఎంచుకోండి",
  "Phone camera videos are supported. Choose an existing recording from Photos/Gallery or Files. Images ≤10 MB · music ≤25 MB · videos/APKs ≤50 MB.": "ఫోన్ కెమెరా వీడియోలకు మద్దతు ఉంది. ఫోటోలు/గ్యాలరీ లేదా ఫైళ్ల నుంచి రికార్డింగ్ ఎంచుకోండి. చిత్రాలు ≤10 MB · సంగీతం ≤25 MB · వీడియోలు/APKలు ≤50 MB.",
  "Ready to upload this Android package.": "ఈ Android ప్యాకేజీ అప్‌లోడ్‌కు సిద్ధంగా ఉంది.",
  "I own this file or have permission to share it, and it is suitable for a public village gallery used by children and adults.": "ఈ ఫైల్ నాదే లేదా పంచుకునే అనుమతి నాకు ఉంది; పిల్లలు, పెద్దలు ఉపయోగించే పబ్లిక్ గ్యాలరీకి ఇది సరైనది.",
  "Public upload": "పబ్లిక్ అప్‌లోడ్",
  "Your nickname, role and upload will be visible to everyone. Do not upload private photos, personal documents, contact details, harmful content, pirated media or APKs you do not trust.": "మీ పేరు, పాత్ర, అప్‌లోడ్ అందరికీ కనిపిస్తాయి. వ్యక్తిగత ఫోటోలు, పత్రాలు, సంప్రదింపు వివరాలు, హానికర కంటెంట్, పైరేటెడ్ మీడియా లేదా నమ్మలేని APKలు అప్‌లోడ్ చేయవద్దు.",
  "Choose a file to continue": "కొనసాగడానికి ఫైల్ ఎంచుకోండి",
  "Uploading…": "అప్‌లోడ్ అవుతోంది…",
  "YOUR UPLOAD · EDIT DETAILS": "మీ అప్‌లోడ్ · వివరాలు సవరించండి",
  "Edit what everyone sees": "అందరికీ కనిపించే వివరాలను సవరించండి",
  "The media file stays unchanged. You can update its public title and description.": "మీడియా ఫైల్ మారదు. పబ్లిక్ శీర్షిక, వివరణను మాత్రమే మార్చవచ్చు.",
  "Add or improve the public description": "పబ్లిక్ వివరణను జోడించండి లేదా మెరుగుపరచండి",
  "You stay in control.": "నియంత్రణ మీ చేతుల్లోనే ఉంటుంది.",
  "Only the account that uploaded this item can edit or delete it. Changes appear in the public gallery after saving.": "ఈ అంశాన్ని అప్‌లోడ్ చేసిన ఖాతానే దాన్ని సవరించగలదు లేదా తొలగించగలదు. సేవ్ చేసిన వెంటనే మార్పులు గ్యాలరీలో కనిపిస్తాయి.",
  "Save changes →": "మార్పులు సేవ్ చేయండి →",
  "Saving…": "సేవ్ అవుతోంది…",
  "Unverified community APK": "ధృవీకరించని సముదాయం APK",
  "Install only if you trust the uploader. KGM does not auto-install community APKs.": "అప్‌లోడర్‌పై నమ్మకం ఉంటేనే ఇన్‌స్టాల్ చేయండి. KGM సముదాయం APKలను ఆటో-ఇన్‌స్టాల్ చేయదు.",

  "THE COMMUNITY SHELF": "సముదాయం షెల్ఫ్",
  "Made in Koratlagudem": "కొరట్లగూడెంలో తయారైంది",
  "Real photos, songs, videos and APKs shared by KGM members. No demo listings and no “coming soon” placeholders.": "KGM సభ్యులు పంచుకున్న నిజమైన ఫోటోలు, పాటలు, వీడియోలు, APKలు. డెమో జాబితాలు లేదా ‘త్వరలో’ ప్లేస్‌హోల్డర్లు లేవు.",
  "REAL": "నిజమైన",
  "UPLOADS": "అప్‌లోడ్లు",
  "Search real community uploads…": "నిజమైన సముదాయం అప్‌లోడ్లలో వెతకండి…",
  "Could not load the live shelf.": "లైవ్ షెల్ఫ్ లోడ్ కాలేదు.",
  "Loading real village uploads…": "మన ఊరి నిజమైన అప్‌లోడ్లు లోడ్ అవుతున్నాయి…",
  "No uploads match this filter yet.": "ఈ ఫిల్టర్‌కు సరిపోయే అప్‌లోడ్లు ఇంకా లేవు.",
  "The community shelf is ready for its first real upload.": "సముదాయం షెల్ఫ్ తన మొదటి నిజమైన అప్‌లోడ్‌కు సిద్ధంగా ఉంది.",
  "Try another type or search term.": "మరో రకం లేదా శోధన పదం ప్రయత్నించండి.",
  "Upload a photo, song, video or APK in Gallery and it will appear here automatically.": "గ్యాలరీలో ఫోటో, పాట, వీడియో లేదా APK అప్‌లోడ్ చేస్తే అది ఇక్కడ స్వయంచాలకంగా కనిపిస్తుంది.",
  "COMMUNITY MUSIC": "సముదాయం సంగీతం",
  "Community Android package": "సముదాయం Android ప్యాకేజీ",
  "Everything here comes from the public KGM Gallery.": "ఇక్కడ ఉన్న ప్రతిదీ పబ్లిక్ KGM గ్యాలరీ నుంచి వస్తుంది.",

  "KGM Village Chat": "KGM గ్రామ చాట్",
  "Restoring your KGM session…": "మీ KGM సెషన్ తిరిగి తెస్తున్నాం…",
  "Sign in to join our village room": "మన ఊరి గదిలో చేరడానికి సైన్ ఇన్ చేయండి",
  "Live public room · Koratlagudem": "ప్రత్యక్ష పబ్లిక్ గది · కొరట్లగూడెం",
  "Trying to reconnect…": "మళ్లీ కనెక్ట్ కావడానికి ప్రయత్నిస్తున్నాం…",
  "Connecting…": "కనెక్ట్ అవుతోంది…",
  "Restoring your KGM account.": "మీ KGM ఖాతాను తిరిగి తెస్తున్నాం.",
  "Your saved login is still here. KGM will reconnect when the network is ready.": "మీ సేవ్ చేసిన లాగిన్ సురక్షితంగా ఉంది. నెట్‌వర్క్ సిద్ధమైన వెంటనే KGM మళ్లీ కనెక్ట్ అవుతుంది.",
  "KGM ACCOUNT · మన ఊరి ఖాతా": "KGM ఖాతా · మన ఊరి ఖాతా",
  "Join our village.": "మన ఊరిలో చేరండి.",
  "Welcome back.": "మళ్లీ స్వాగతం.",
  "Create a simple account for Village Chat. Your email stays private; only your nickname and role appear publicly.": "గ్రామ చాట్ కోసం సులభమైన ఖాతా సృష్టించండి. మీ ఈమెయిల్ గోప్యంగా ఉంటుంది; మీ పేరు, పాత్ర మాత్రమే అందరికీ కనిపిస్తాయి.",
  "Sign in with the email and password you used when creating your KGM account.": "మీ KGM ఖాతా సృష్టించినప్పుడు ఉపయోగించిన ఈమెయిల్, పాస్‌వర్డ్‌తో సైన్ ఇన్ చేయండి.",
  "Minimum 4 characters": "కనీసం 4 అక్షరాలు",
  "I am joining as": "నేను ఇలా చేరుతున్నాను",
  "I’ll keep the room friendly and won’t share personal contact information.": "గదిని స్నేహపూర్వకంగా ఉంచి, వ్యక్తిగత సంప్రదింపు వివరాలు పంచుకోను.",
  "No email verification for now.": "ప్రస్తుతం ఈమెయిల్ ధృవీకరణ అవసరం లేదు.",
  "Any valid email format can register immediately. Passwords are still stored securely as hashes.": "సరైన ఈమెయిల్ ఆకృతితో వెంటనే నమోదు చేసుకోవచ్చు. పాస్‌వర్డ్‌లు హాష్‌లుగా సురక్షితంగా నిల్వ చేయబడతాయి.",
  "Please wait…": "దయచేసి వేచి ఉండండి…",
  "Create account & enter chat →": "ఖాతా సృష్టించి చాట్‌లో చేరండి →",
  "Sign in & open chat →": "సైన్ ఇన్ చేసి చాట్ తెరవండి →",
  "Public village room.": "పబ్లిక్ గ్రామ గది.",
  "No DMs, photos, links, phone numbers or email addresses. Report anything uncomfortable.": "ప్రైవేట్ సందేశాలు, ఫోటోలు, లింకులు, ఫోన్ నంబర్లు లేదా ఈమెయిల్ చిరునామాలు వద్దు. అసౌకర్యంగా అనిపించినదాన్ని ఫిర్యాదు చేయండి.",
  "🔔 Alerts on": "🔔 హెచ్చరికలు ఆన్",
  "🔕 Alerts blocked": "🔕 హెచ్చరికలు నిలిపివేయబడ్డాయి",
  "🔔 Notify me": "🔔 నాకు తెలియజేయండి",
  "Start today’s village conversation.": "ఈరోజు మన ఊరి సంభాషణను ప్రారంభించండి.",
  "Ask about school, farming, science, sports, local events—or simply say hello.": "పాఠశాల, వ్యవసాయం, సైన్స్, క్రీడలు, స్థానిక కార్యక్రమాలు గురించి అడగండి — లేదా హలో చెప్పండి.",
  "Write something friendly…": "స్నేహపూర్వకంగా ఏదైనా రాయండి…",
  "Personal contact details and links are blocked.": "వ్యక్తిగత సంప్రదింపు వివరాలు, లింకులు నిరోధించబడ్డాయి.",
  "New Village Chat message": "కొత్త గ్రామ చాట్ సందేశం",
  "Tap to open KGM Village Chat.": "KGM గ్రామ చాట్ తెరవడానికి ట్యాప్ చేయండి.",
  "You are offline": "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు",
  "KGM’s saved app shell remains available. Chat, gallery and downloads reconnect when the network returns.": "KGM సేవ్ చేసిన యాప్ భాగం అందుబాటులోనే ఉంటుంది. నెట్‌వర్క్ తిరిగి వచ్చినప్పుడు చాట్, గ్యాలరీ, డౌన్‌లోడ్లు మళ్లీ కనెక్ట్ అవుతాయి.",
  "Updating KGM…": "KGM నవీకరించబడుతోంది…",
  "The latest mobile improvements are being activated automatically.": "తాజా మొబైల్ మెరుగుదలలు స్వయంచాలకంగా అమలవుతున్నాయి.",
  "Update now": "ఇప్పుడే నవీకరించండి",

  "KGM SCIENCE CINEMA": "KGM సైన్స్ సినిమా",
  "STEM ONLY · FREE KNOWLEDGE": "STEM మాత్రమే · ఉచిత జ్ఞానం",
  "Space": "అంతరిక్షం",
  "Physics": "భౌతిక శాస్త్రం",
  "Life": "జీవశాస్త్రం",
  "Biology": "జీవశాస్త్రం",
  "Earth": "భూమి",
  "Engineering": "ఇంజినీరింగ్",
  "Kids Science": "పిల్లల సైన్స్",
  "Mathematics": "గణితం",
  "Medicine": "వైద్యం",
  "Scientists": "శాస్త్రవేత్తలు",
  "Technology": "సాంకేతికత",
  "Telugu Science": "తెలుగు సైన్స్",
  "KGM° FEATURED SCIENCE": "KGM° ప్రత్యేక సైన్స్",
  "▶ Watch inside KGM": "▶ KGMలో చూడండి",
  "＋ My List": "＋ నా జాబితా",
  "✓ In My List": "✓ నా జాబితాలో ఉంది",
  "Search black holes, DNA, engineering…": "బ్లాక్ హోల్స్, DNA, ఇంజినీరింగ్‌లో వెతకండి…",
  "CONTINUE WATCHING": "చూడటం కొనసాగించండి",
  "Pick up where you left off.": "మీరు ఆపిన చోట నుంచే కొనసాగించండి.",
  "STEM LIBRARY": "STEM గ్రంథాలయం",
  "Loading the science shelf…": "సైన్స్ షెల్ఫ్ లోడ్ అవుతోంది…",
  "🛡 STEM-only curation": "🛡 STEM మాత్రమే ఎంపిక",
  "No films in this filter yet.": "ఈ ఫిల్టర్‌లో ఇంకా సినిమాలు లేవు.",
  "Try another STEM topic.": "మరో STEM అంశాన్ని ప్రయత్నించండి.",
  "STEM only.": "STEM మాత్రమే.",
  "Space, physics, life, Earth, medicine, engineering, technology and mathematics.": "అంతరిక్షం, భౌతిక శాస్త్రం, జీవం, భూమి, వైద్యం, ఇంజినీరింగ్, సాంకేతికత, గణితం.",
  "Watch legally.": "చట్టబద్ధంగా చూడండి.",
  "Official embeds or KGM-hosted films with public-domain, Creative Commons, NASA or explicit redistribution rights.": "అధికారిక ఎంబెడ్లు లేదా పబ్లిక్ డొమైన్, Creative Commons, NASA లేదా స్పష్టమైన పునర్వితరణ హక్కులతో KGM హోస్ట్ చేసిన చిత్రాలు మాత్రమే.",
  "Learn, don’t just scroll.": "స్క్రోల్ చేయడమే కాదు — నేర్చుకోండి.",
  "Every film is paired with concepts, questions and a reason to stay curious.": "ప్రతి చిత్రంతో భావనలు, ప్రశ్నలు, జిజ్ఞాసను కొనసాగించే కారణం ఉంటాయి.",
  "WATCH → NOTICE → EXPLAIN": "చూడండి → గమనించండి → వివరించండి",
  "Science inside this film": "ఈ చిత్రంలోని సైన్స్",
  "After watching, can you explain…": "చూసిన తర్వాత మీరు వివరించగలరా…",
  "What new idea did you learn?": "మీరు ఏ కొత్త ఆలోచన నేర్చుకున్నారు?",
  "What evidence did the film show?": "ఈ చిత్రం ఏ ఆధారాన్ని చూపించింది?",
  "What question would you investigate next?": "తర్వాత మీరు ఏ ప్రశ్నను పరిశీలిస్తారు?",
  "♥ Liked": "♥ నచ్చింది",
  "♡ Like": "♡ నచ్చింది",
  "✓ My List": "✓ నా జాబితా",
  "KGM CURATOR DESK": "KGM క్యూరేటర్ డెస్క్",
  "Add STEM cinema": "STEM సినిమా జోడించండి",
  "YouTube embed": "YouTube ఎంబెడ్",
  "Render-hosted movie": "Render హోస్ట్ చేసిన చిత్రం",
  "Category": "వర్గం",
  "Channel": "ఛానల్",
  "Age rating": "వయస్సు రేటింగ్",
  "Duration": "నిడివి",
  "Topics": "అంశాలు",
  "What learners should be able to explain": "విద్యార్థులు వివరించగలగాల్సిన విషయాలు",
  "Attribution": "మూల గుర్తింపు",
  "Source page": "మూల పేజీ",
  "This is genuinely STEM/educational content.": "ఇది నిజమైన STEM/విద్యా కంటెంట్.",
  "The publisher allows playback through the official YouTube embed.": "అధికారిక YouTube ఎంబెడ్ ద్వారా ప్లేబ్యాక్‌కు ప్రచురణకర్త అనుమతిస్తారు.",
  "Adding…": "జోడిస్తోంది…",
  "Add to Science Cinema →": "సైన్స్ సినిమాకు జోడించండి →",
  "Render disk only.": "Render డిస్క్ మాత్రమే.",
  "Movie file": "సినిమా ఫైల్",
  "License": "లైసెన్స్",
  "Public domain": "పబ్లిక్ డొమైన్",
  "NASA media": "NASA మీడియా",
  "Explicit permission": "స్పష్టమైన అనుమతి",

  "Manage uploads": "అప్‌లోడ్లు నిర్వహించండి",
  "Edit song details": "పాట వివరాలు సవరించండి",
  "MY KGM MUSIC": "నా KGM సంగీతం",
  "Edit uploaded songs": "అప్‌లోడ్ చేసిన పాటలను సవరించండి",
  "Change the visible song details without uploading the audio again.": "ఆడియోను మళ్లీ అప్‌లోడ్ చేయకుండా కనిపించే పాట వివరాలను మార్చండి.",
  "Edit →": "సవరించండి →",
  "← All uploads": "← అన్ని అప్‌లోడ్లు",
  "Audio file": "ఆడియో ఫైల్",
  "The audio file itself is never replaced by this edit.": "ఈ సవరణలో అసలు ఆడియో ఫైల్ మారదు.",
  "Song title": "పాట శీర్షిక",
  "Artist / singer": "కళాకారుడు / గాయకుడు",
  "Language": "భాష",
  "Song title and artist are required.": "పాట శీర్షిక, కళాకారుడి పేరు అవసరం.",
  "Song details updated. Refreshing KGM so the player and cards use the new metadata…": "పాట వివరాలు నవీకరించబడ్డాయి. కొత్త వివరాలు కనిపించేందుకు KGM రిఫ్రెష్ అవుతోంది…",
  "Could not update this song. Check browser storage permissions.": "ఈ పాటను నవీకరించలేకపోయాం. బ్రౌజర్ స్టోరేజ్ అనుమతులను తనిఖీ చేయండి.",

  "KGM DESKTOP APP": "KGM డెస్క్‌టాప్ యాప్",
  "Install KGM on this computer": "ఈ కంప్యూటర్లో KGM ఇన్‌స్టాల్ చేయండి",
  "KGM opens in its own window and appears in your Start menu and taskbar. There is no installer file to download.": "KGM ప్రత్యేక విండోలో తెరుచుకుని Start మెనూ, టాస్క్‌బార్‌లో కనిపిస్తుంది. వేరే ఇన్‌స్టాలర్ ఫైల్ అవసరం లేదు.",
  "Open this page in Chrome or Microsoft Edge": "ఈ పేజీని Chrome లేదా Microsoft Edgeలో తెరవండి",
  "Use the current, secure KGM website on Render.": "Renderలో ఉన్న ప్రస్తుత సురక్షిత KGM వెబ్‌సైట్‌ను ఉపయోగించండి.",
  "Open the browser menu": "బ్రౌజర్ మెనూను తెరవండి",
  "Confirm Install": "ఇన్‌స్టాల్‌ను నిర్ధారించండి",
  "Pin KGM to the taskbar or Start menu if your browser offers those options.": "మీ బ్రౌజర్ అనుమతిస్తే KGMను టాస్క్‌బార్ లేదా Start మెనూకు పిన్ చేయండి.",
  "Got it": "అర్థమైంది",
  "If the Install option is missing, refresh once after this update finishes deploying.": "Install ఎంపిక కనిపించకపోతే ఈ నవీకరణ పూర్తయ్యాక ఒకసారి రిఫ్రెష్ చేయండి.",
  "PC app installed": "PC యాప్ ఇన్‌స్టాల్ అయింది",
  "Install on PC": "PCలో ఇన్‌స్టాల్ చేయండి",

  "KGM PROFILE LAB": "KGM ప్రొఫైల్ ల్యాబ్",
  "Make it yours.": "దీన్ని మీలా మార్చుకోండి.",
  "Your nickname, role, avatar and Science Cinema library travel with your KGM account.": "మీ పేరు, పాత్ర, అవతార్, సైన్స్ సినిమా గ్రంథాలయం మీ KGM ఖాతాతో పాటు ఉంటాయి.",
  "Loading your KGM identity…": "మీ KGM గుర్తింపును లోడ్ చేస్తున్నాం…",
  "YOUR KGM ID": "మీ KGM గుర్తింపు",
  "Koratlagudem Youthverse": "కొరట్లగూడెం యూత్‌వర్స్",
  "✦ CREATOR": "✦ సృష్టికర్త",
  "⚡ KGM MEMBER": "⚡ KGM సభ్యుడు",
  "I’m joining as": "నేను ఇలా చేరుతున్నాను",
  "Your curiosity shelf.": "మీ జిజ్ఞాస షెల్ఫ్.",
  "Open Cinema →": "సినిమా తెరవండి →",
  "Liked films": "నచ్చిన సినిమాలు",
  "My STEM List": "నా STEM జాబితా",
  "♥ LIKED SCIENCE FILMS": "♥ నచ్చిన సైన్స్ సినిమాలు",

  "Primary navigation": "ప్రధాన నావిగేషన్",
  "KGM Youthverse navigation": "KGM యూత్‌వర్స్ నావిగేషన్",
  "KGM Youthverse home": "KGM యూత్‌వర్స్ హోమ్",
  "Toggle light or dark appearance": "లైట్ లేదా డార్క్ రూపాన్ని మార్చండి",
  "Open KGM menu": "KGM మెనూ తెరవండి",
  "Close gallery": "గ్యాలరీ మూసివేయండి",
  "Close chat": "చాట్ మూసివేయండి",
  "Close Science Cinema": "సైన్స్ సినిమా మూసివేయండి",
  "Close movie": "సినిమా మూసివేయండి",
  "Close profile editor": "ప్రొఫైల్ సవరణ మూసివేయండి",
  "Close install instructions": "ఇన్‌స్టాల్ సూచనలు మూసివేయండి",
  "Search community uploads": "సముదాయం అప్‌లోడ్లలో వెతకండి",
  "Filter community uploads": "సముదాయం అప్‌లోడ్లను ఫిల్టర్ చేయండి",
  "KGM mobile navigation": "KGM మొబైల్ నావిగేషన్",
  "Explore KGM creative spaces": "KGM సృజనాత్మక విభాగాలను అన్వేషించండి",
  "Koratlagudem creations shared everywhere through KGM": "కొరట్లగూడెం సృష్టులు KGM ద్వారా ప్రపంచమంతా పంచబడుతున్నాయి",
  "KGM amplifier": "KGM విస్తారక కేంద్రం",
  "KGM village mission": "KGM గ్రామ లక్ష్యం"
};

const ROLE_TE: Record<string, string> = { Child: "పిల్లవాడు/పిల్ల", Teen: "యువకుడు/యువతి", Adult: "పెద్దవారు" };
const MONTH_TE: Record<string, string> = {
  Jan: "జన", Feb: "ఫిబ్ర", Mar: "మార్చి", Apr: "ఏప్రి", May: "మే", Jun: "జూన్",
  Jul: "జూలై", Aug: "ఆగ", Sep: "సెప్", Oct: "అక్టో", Nov: "నవం", Dec: "డిసెం"
};

function translateDateParts(value: string) {
  return value.replace(/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b/g, (month) => MONTH_TE[month] || month);
}

export function translateKgmUiText(input: string): string {
  const value = input.trim();
  if (!value) return value;
  if (KGM_TE[value]) return KGM_TE[value];

  let match = value.match(/^Yo (.+?) 👋 see what our village is creating today\.$/);
  if (match) return `హాయ్ ${match[1]} 👋 ఈ రోజు మన ఊరు ఏమి సృష్టిస్తుందో చూడండి.`;

  match = value.match(/^by (.+)$/);
  if (match) return `${match[1]} ద్వారా`;

  match = value.match(/^(Child|Teen|Adult) · (.+)$/);
  if (match) return `${ROLE_TE[match[1]] || match[1]} · ${translateDateParts(match[2])}`;

  match = value.match(/^(\d+) kids · (\d+) teens · (\d+) adults in recent chat$/);
  if (match) return `ఇటీవలి చాట్‌లో ${match[1]} పిల్లలు · ${match[2]} యువకులు · ${match[3]} పెద్దవారు`;

  match = value.match(/^(\d+) ways to get curious\.$/);
  if (match) return `జిజ్ఞాస పెంచే ${match[1]} మార్గాలు.`;

  match = value.match(/^(\d+) public community uploads$/);
  if (match) return `${match[1]} పబ్లిక్ సముదాయం అప్‌లోడ్లు`;

  match = value.match(/^Showing the latest (\d+) of (\d+) matching uploads\.$/);
  if (match) return `సరిపోయే ${match[2]} అప్‌లోడ్లలో తాజా ${match[1]} చూపిస్తున్నాం.`;

  match = value.match(/^(\d+) unread messages$/);
  if (match) return `${match[1]} చదవని సందేశాలు`;

  match = value.match(/^(\d+) new Village Chat messages$/);
  if (match) return `${match[1]} కొత్త గ్రామ చాట్ సందేశాలు`;

  match = value.match(/^(\d+) new KGM Village Chat messages$/);
  if (match) return `${match[1]} కొత్త KGM గ్రామ చాట్ సందేశాలు`;

  match = value.match(/^Open (.+)$/);
  if (match) return `${match[1]} తెరవండి`;

  match = value.match(/^Edit (.+)'s profile$/);
  if (match) return `${match[1]} ప్రొఫైల్‌ను సవరించండి`;

  match = value.match(/^SELECTED (IMAGE|VIDEO|AUDIO|APK)$/);
  if (match) return `ఎంచుకున్న ${KGM_TE[match[1][0] + match[1].slice(1).toLowerCase()] || match[1]}`;

  match = value.match(/^Publish (image|video|audio|apk) for everyone →$/i);
  if (match) {
    const kind = match[1].toLowerCase();
    const label = kind === "image" ? "చిత్రాన్ని" : kind === "video" ? "వీడియోను" : kind === "audio" ? "ఆడియోను" : "APKను";
    return `${label} అందరికీ పంచండి →`;
  }

  match = value.match(/^(\d+)\/280 · Personal contact details and links are blocked\.$/);
  if (match) return `${match[1]}/280 · వ్యక్తిగత సంప్రదింపు వివరాలు, లింకులు నిరోధించబడ్డాయి.`;

  return translateDateParts(value);
}
