const LEGACY_TE: Record<string, string> = {
  "Learning": "అభ్యాసం",
  "Games": "ఆటలు",
  "Village": "మన ఊరు",
  "Tools": "సాధనాలు",
  "My uploads": "నా అప్‌లోడ్లు",
  "Preview": "ప్రివ్యూ",
  "Concept": "ఆలోచన దశ",
  "Coming soon": "త్వరలో",
  "In development": "అభివృద్ధిలో ఉంది",
  "Concept stage": "ఆలోచన దశ",
  "Everyone": "అందరికీ",
  "No account": "ఖాతా అవసరం లేదు",
  "No location": "లొకేషన్ అవసరం లేదు",
  "No ads": "ప్రకటనలు లేవు",
  "Works offline": "ఆఫ్‌లైన్‌లో పనిచేస్తుంది",
  "No tracking": "ట్రాకింగ్ లేదు",
  "No contacts": "కాంటాక్ట్స్ అవసరం లేదు",
  "Offline first": "ఆఫ్‌లైన్‌కు ప్రాధాన్యం",
  "No camera": "కెమెరా అవసరం లేదు",
  "Local data only": "స్థానిక డేటా మాత్రమే",
  "Public Domain": "పబ్లిక్ డొమైన్",
  "Owned by uploader": "అప్‌లోడర్‌కు చెందినది",
  "Local song": "స్థానిక పాట",
  "KGM community upload": "KGM సముదాయం అప్‌లోడ్",
  "Stored privately in this browser and played inside KGM.": "ఈ బ్రౌజర్‌లో గోప్యంగా నిల్వై KGMలోనే ప్లే అవుతుంది.",

  "Explore apps": "యాప్స్ అన్వేషించండి",
  "Built in Koratlagudem · Shared with everyone": "కొరట్లగూడెంలో నిర్మించాం · అందరితో పంచుకున్నాం",
  "Small village.": "చిన్న ఊరు.",
  "Big ideas.": "పెద్ద ఆలోచనలు.",
  "Apps for everyone.": "అందరికీ యాప్స్.",
  "The community home for safe, useful Android apps imagined and built by the young creators of Koratlagudem.": "కొరట్లగూడెం యువ సృష్టికర్తలు ఆలోచించి నిర్మించిన సురక్షితమైన, ఉపయోగకరమైన Android యాప్స్‌కు మన సముదాయం హోమ్.",
  "Explore the apps": "యాప్స్ చూడండి",
  "Play KGM music": "KGM సంగీతం వినండి",
  "Mentor-reviewed releases": "మెంటర్ సమీక్షించిన విడుదలలు",
  "Clear permissions": "స్పష్టమైన అనుమతులు",
  "Music plays here": "సంగీతం ఇక్కడే వినిపిస్తుంది",
  "What will you discover?": "మీరు ఏమి కనుగొంటారు?",
  "Search KGM apps": "KGM యాప్స్‌లో వెతకండి",
  "FEATURED": "ప్రత్యేకం",
  "ideas growing": "పెరుగుతున్న ఆలోచనలు",
  "Imagine": "ఆలోచించండి",
  "A child spots a problem worth solving.": "ఒక పిల్లవాడు పరిష్కరించదగ్గ సమస్యను గుర్తిస్తాడు.",
  "Build": "నిర్మించండి",
  "They turn curiosity into working code.": "జిజ్ఞాసను పనిచేసే కోడ్‌గా మార్చుతారు.",
  "Share": "పంచుకోండి",
  "A safe release reaches the community.": "సురక్షితమైన విడుదల సముదాయానికి చేరుతుంది.",
  "Fresh ideas from young builders. Published apps will include a verified APK, version details and a safety note.": "యువ నిర్మాణకర్తల తాజా ఆలోచనలు. ప్రచురించిన యాప్స్‌లో ధృవీకరించిన APK, వెర్షన్ వివరాలు, భద్రతా గమనిక ఉంటాయి.",
  "Search apps": "యాప్స్‌లో వెతకండి",
  "Search apps, creators or categories…": "యాప్స్, సృష్టికర్తలు లేదా వర్గాల్లో వెతకండి…",
  "View details": "వివరాలు చూడండి",
  "In the lab": "ల్యాబ్‌లో ఉంది",

  "Quick number challenges made for curious minds.": "జిజ్ఞాస కలిగిన మనసులకు వేగవంతమైన సంఖ్యా సవాళ్లు.",
  "A fast, friendly practice game for arithmetic, patterns and mental maths—with short rounds that work well at home or in the classroom.": "అంకగణితం, నమూనాలు, మానసిక గణితానికి వేగవంతమైన స్నేహపూర్వక సాధన ఆట — ఇంట్లోనూ తరగతిలోనూ సరిపోయే చిన్న రౌండ్లతో.",
  "Discover our village, Telangana and India.": "మన ఊరు, తెలంగాణ, భారతదేశాన్ని తెలుసుకోండి.",
  "A local-first quiz about geography, culture, science and community knowledge, designed to turn everyday surroundings into questions worth exploring.": "భూగోళం, సంస్కృతి, సైన్స్, సముదాయం జ్ఞానంపై స్థానికతకు ప్రాధాన్యమిచ్చే క్విజ్ — రోజువారీ పరిసరాలను అన్వేషించదగ్గ ప్రశ్నలుగా మార్చుతుంది.",
  "A pocket launchpad for young space explorers.": "యువ అంతరిక్ష అన్వేషకులకు జేబులో ఉండే లాంచ్‌ప్యాడ్.",
  "Explore planets, space missions and astronomy challenges through playful missions created for children who look up and ask why.": "ఆకాశాన్ని చూసి ‘ఎందుకు?’ అని అడిగే పిల్లల కోసం రూపొందించిన సరదా మిషన్లతో గ్రహాలు, అంతరిక్ష ప్రయాణాలు, ఖగోళ సవాళ్లను అన్వేషించండి.",
  "Build Telugu vocabulary one playful word at a time.": "ఒక్కో సరదా పదంతో తెలుగు పదసంపదను పెంచుకోండి.",
  "Picture-led word practice, small spelling challenges and local expressions that help children learn Telugu with confidence.": "చిత్రాలతో పదాభ్యాసం, చిన్న అక్షర దోష సవాళ్లు, స్థానిక పదప్రయోగాలతో పిల్లలు ధైర్యంగా తెలుగు నేర్చుకునేలా చేస్తుంది.",
  "Tiny missions for a cleaner, greener village.": "శుభ్రమైన, పచ్చని ఊరి కోసం చిన్న మిషన్లు.",
  "Complete practical nature missions, learn about waste and water, and build planet-friendly habits without sharing personal information.": "ప్రకృతి మిషన్లు పూర్తి చేసి, వ్యర్థాలు, నీటి గురించి నేర్చుకుని, వ్యక్తిగత సమాచారం పంచుకోకుండా పర్యావరణహిత అలవాట్లు పెంచుకోండి.",
  "A calm homework and revision companion.": "హోంవర్క్, పునశ్చరణకు ప్రశాంత సహచరి.",
  "Create simple study sessions, use focus timers and keep revision goals on the device. No sign-in and no cloud profile required.": "సులభమైన అధ్యయన సెషన్లు రూపొందించండి, ఫోకస్ టైమర్లు ఉపయోగించండి, పునశ్చరణ లక్ష్యాలను పరికరంలోనే ఉంచండి. సైన్ ఇన్ లేదా క్లౌడ్ ప్రొఫైల్ అవసరం లేదు.",

  "KGM FOLK RADIO · గ్రామ స్వరాలు": "KGM జానపద రేడియో · గ్రామ స్వరాలు",
  "Stay in KGM.": "KGMలోనే ఉండండి.",
  "Let the village play.": "మన ఊరి స్వరాలు వినిపించనివ్వండి.",
  "Songs now play directly inside KGM. Add your own village recordings too, and keep browsing while the music continues.": "పాటలు ఇప్పుడు KGMలోనే నేరుగా వినిపిస్తాయి. మీ ఊరి రికార్డింగులను కూడా జోడించి, సంగీతం వినిపిస్తూనే అన్వేషించండి.",
  "✓ In-app audio player": "✓ యాప్‌లోనే ఆడియో ప్లేయర్",
  "✓ Telugu + English folk": "✓ తెలుగు + ఆంగ్ల జానపదం",
  "✓ Your own uploads": "✓ మీ స్వంత అప్‌లోడ్లు",
  "Close uploader": "అప్‌లోడర్ మూసివేయండి",
  "Add your song": "మీ పాట జోడించండి",
  "YOUR MUSIC · మీ పాటలు": "మీ సంగీతం · మీ పాటలు",
  "Add a song to KGM": "KGMకు పాట జోడించండి",
  "This version stores the audio on this browser/device using IndexedDB, so it stays private and plays inside KGM. For a song that everyone should hear, add the approved audio file to the repo’s public/music folder later.": "ఈ వెర్షన్ ఆడియోను IndexedDBతో ఈ బ్రౌజర్/పరికరంలోనే గోప్యంగా నిల్వ చేస్తుంది; అది KGMలో ప్లే అవుతుంది. అందరూ వినాల్సిన పాట అయితే, అనుమతించిన ఆడియో ఫైల్‌ను తర్వాత repoలోని public/music ఫోల్డర్‌కు జోడించండి.",
  "Audio file": "ఆడియో ఫైల్",
  "I own this recording or have permission to use it.": "ఈ రికార్డింగ్ నాదే లేదా ఉపయోగించే అనుమతి నాకు ఉంది.",
  "Add to KGM": "KGMకు జోడించండి",
  "My upload": "నా అప్‌లోడ్",
  "Pause": "ఆపండి",
  "Play in KGM": "KGMలో ప్లే చేయండి",
  "Source ↗": "మూలం ↗",
  "Your KGM music shelf is empty": "మీ KGM సంగీత షెల్ఫ్ ఖాళీగా ఉంది",
  "Use “Add your song” to bring in your own village recording.": "మీ ఊరి రికార్డింగ్‌ను జోడించడానికి ‘మీ పాట జోడించండి’ ఉపయోగించండి.",
  "Two safe music paths.": "సంగీతానికి రెండు సురక్షిత మార్గాలు.",
  "Personal uploads remain on the current browser/device. Curated public tracks stream through KGM’s player from sources with clear reuse terms; the source remains visible for attribution.": "వ్యక్తిగత అప్‌లోడ్లు ఈ బ్రౌజర్/పరికరంలోనే ఉంటాయి. స్పష్టమైన పునర్వినియోగ నిబంధనలు ఉన్న మూలాల నుంచి ఎంపిక చేసిన పబ్లిక్ ట్రాక్‌లు KGM ప్లేయర్‌లో స్ట్రీమ్ అవుతాయి; మూలం గుర్తింపుకోసం కనిపిస్తుంది.",
  "Add the audio, title and artist, then confirm you own it or have permission.": "ఆడియో, శీర్షిక, కళాకారుడి పేరును జోడించి, అది మీదేనని లేదా అనుమతి ఉందని నిర్ధారించండి.",
  "Please keep each upload under 25 MB.": "ప్రతి అప్‌లోడ్‌ను 25 MBలోపు ఉంచండి.",
  "Use MP3, WAV, M4A, OGG or WebM audio.": "MP3, WAV, M4A, OGG లేదా WebM ఆడియో ఉపయోగించండి.",
  "Added to My uploads. It now plays inside KGM on this device.": "నా అప్‌లోడ్లకు జోడించబడింది. ఇప్పుడు ఈ పరికరంలో KGMలో ప్లే అవుతుంది.",
  "Could not save this file locally. Check browser storage permissions.": "ఈ ఫైల్‌ను స్థానికంగా సేవ్ చేయలేకపోయాం. బ్రౌజర్ స్టోరేజ్ అనుమతులను తనిఖీ చేయండి.",
  "Local music storage is unavailable in this browser.": "ఈ బ్రౌజర్‌లో స్థానిక సంగీత స్టోరేజ్ అందుబాటులో లేదు.",

  "BEFORE ANY “INSTALL”": "ఏ ‘ఇన్‌స్టాల్’కైనా ముందు",
  "Trust is a feature.": "నమ్మకం కూడా ఒక ఫీచర్.",
  "We build it in.": "దాన్నే మేము నిర్మాణంలో భాగం చేస్తాం.",
  "Community software should be easy to understand—not a mystery box. Each published APK must pass a simple, visible review before its download button goes live.": "సముదాయం సాఫ్ట్‌వేర్ అర్థం చేసుకోవడానికి సులభంగా ఉండాలి — రహస్య పెట్టెలా కాదు. ప్రతి ప్రచురిత APK డౌన్‌లోడ్ బటన్ అందుబాటులోకి రావడానికి ముందు సరళమైన, స్పష్టమైన సమీక్షను దాటాలి.",
  "See the open-source project": "ఓపెన్ సోర్స్ ప్రాజెక్ట్ చూడండి",
  "Malware scan": "మాల్వేర్ స్కాన్",
  "Every release file is scanned before publishing.": "ప్రతి విడుదల ఫైల్ ప్రచురణకు ముందు స్కాన్ చేయబడుతుంది.",
  "Permission check": "అనుమతుల తనిఖీ",
  "Camera, location and storage access must be justified.": "కెమెరా, లొకేషన్, స్టోరేజ్ యాక్సెస్‌కు స్పష్టమైన కారణం ఉండాలి.",
  "Mentor review": "మెంటర్ సమీక్ష",
  "An adult reviewer checks content and privacy.": "ఒక పెద్దవారి సమీక్షకుడు కంటెంట్, గోప్యతను తనిఖీ చేస్తారు.",
  "Version history": "వెర్షన్ చరిత్ర",
  "Creator, version and update notes stay visible.": "సృష్టికర్త, వెర్షన్, నవీకరణ గమనికలు కనిపిస్తూనే ఉంటాయి.",

  "FOR KORATLAGUDEM’S NEXT GENERATION": "కొరట్లగూడెం తదుపరి తరానికి",
  "YOUNG CREATOR? START HERE.": "యువ సృష్టికర్తా? ఇక్కడ మొదలుపెట్టండి.",
  "Your first app does not need to be perfect.": "మీ మొదటి యాప్ పరిపూర్ణంగా ఉండాల్సిన అవసరం లేదు.",
  "It needs to be yours.": "అది మీదై ఉండాలి.",
  "Bring a useful idea, a working Android build and what you learned. A mentor can help check privacy, permissions and the release details before it joins the community shelf.": "ఒక ఉపయోగకరమైన ఆలోచన, పనిచేసే Android బిల్డ్, మీరు నేర్చుకున్నది తీసుకురండి. సముదాయం షెల్ఫ్‌లో చేరే ముందు గోప్యత, అనుమతులు, విడుదల వివరాలను మెంటర్ తనిఖీ చేయడంలో సహాయపడతారు.",
  "Submit an app": "యాప్ సమర్పించండి",
  "View the project": "ప్రాజెక్ట్ చూడండి",
  "Made with curiosity in Koratlagudem, Telangana.": "తెలంగాణలోని కొరట్లగూడెంలో జిజ్ఞాసతో రూపొందించాం.",
  "Submit": "సమర్పించండి",

  "NOW PLAYING IN KGM": "ఇప్పుడు KGMలో వినిపిస్తోంది",
  "Preview listing": "ప్రివ్యూ జాబితా",
  "VERSION": "వెర్షన్",
  "SIZE": "పరిమాణం",
  "REQUIRES": "అవసరం",
  "Privacy at a glance": "గోప్యత ఒక చూపులో",
  "Created by": "సృష్టించిన వారు",
  "APK coming after safety review": "భద్రతా సమీక్ష తర్వాత APK వస్తుంది",
  "This is a transparent preview listing—not a published APK.": "ఇది పారదర్శక ప్రివ్యూ జాబితా మాత్రమే — ప్రచురిత APK కాదు.",

  "Koratlagudem APK Hub home": "కొరట్లగూడెం APK హబ్ హోమ్",
  "Toggle navigation": "నావిగేషన్ మార్చండి",
  "KGM music player": "KGM సంగీత ప్లేయర్",
  "Close player": "ప్లేయర్ మూసివేయండి",
  "Remove upload": "అప్‌లోడ్ తొలగించండి"
};

export function translateLegacyKgmUiText(input: string): string {
  const value = input.trim();
  if (LEGACY_TE[value]) return LEGACY_TE[value];

  let match = value.match(/^Ages (\d+)\+$/);
  if (match) return `${match[1]}+ వయస్సులకు`;

  match = value.match(/^Android (\d+)\+ planned$/);
  if (match) return `Android ${match[1]}+ కోసం ప్రణాళికలో`;

  match = value.match(/^(\d+) ideas growing$/);
  if (match) return `పెరుగుతున్న ${match[1]} ఆలోచనలు`;

  return value;
}
