"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import AndroidInstall from "./AndroidInstall";
import { PwaInstallButton } from "./PwaInstall";

type Category = "All" | "Learning" | "Games" | "Village" | "Tools";
type MusicLanguage = "All" | "Telugu" | "English / Folk" | "My uploads";
type AppEntry = { id:string; name:string; teluguName:string; tagline:string; description:string; category:Exclude<Category,"All">; version:string; size:string; android:string; updated:string; maker:string; age:string; permissions:string[]; icon:string; accent:string; apkUrl?:string; featured?:boolean };
type Track = { id:string; title:string; teluguTitle?:string; artist:string; language:"Telugu"|"English / Folk"; mood:string; duration:string; license:string; sourceUrl?:string; audioUrl:string; note:string; icon:string; uploaded?:boolean };
type StoredSong = { id:string; title:string; artist:string; language:"Telugu"|"English / Folk"; fileName:string; mimeType:string; blob:Blob; createdAt:number };

const apps: AppEntry[] = [
  { id:"math-sprint", name:"KGM Math Sprint", teluguName:"కేజీఎం మ్యాథ్ స్ప్రింట్", tagline:"Quick number challenges made for curious minds.", description:"A fast, friendly practice game for arithmetic, patterns and mental maths—with short rounds that work well at home or in the classroom.", category:"Learning", version:"Preview", size:"Coming soon", android:"Android 8+ planned", updated:"In development", maker:"KGM Young Coders", age:"Ages 8+", permissions:["No account","No location","No ads"], icon:"π", accent:"#ff6b35", featured:true },
  { id:"mana-ooru", name:"Mana Ooru Quiz", teluguName:"మన ఊరు క్విజ్", tagline:"Discover our village, Telangana and India.", description:"A local-first quiz about geography, culture, science and community knowledge, designed to turn everyday surroundings into questions worth exploring.", category:"Village", version:"Preview", size:"Coming soon", android:"Android 8+ planned", updated:"In development", maker:"Koratlagudem Learners", age:"Everyone", permissions:["Works offline","No tracking","No ads"], icon:"ఊ", accent:"#12a594", featured:true },
  { id:"kspace-explorer", name:"KSpace Explorer", teluguName:"కేస్పేస్ ఎక్స్‌ప్లోరర్", tagline:"A pocket launchpad for young space explorers.", description:"Explore planets, space missions and astronomy challenges through playful missions created for children who look up and ask why.", category:"Learning", version:"Preview", size:"Coming soon", android:"Android 9+ planned", updated:"In development", maker:"KGM Space Club", age:"Ages 9+", permissions:["No account","No contacts","No ads"], icon:"↗", accent:"#7657ed", featured:true },
  { id:"telugu-bloom", name:"Telugu Word Bloom", teluguName:"తెలుగు పద వికాసం", tagline:"Build Telugu vocabulary one playful word at a time.", description:"Picture-led word practice, small spelling challenges and local expressions that help children learn Telugu with confidence.", category:"Learning", version:"Concept", size:"Coming soon", android:"Android 8+ planned", updated:"Concept stage", maker:"KGM Language Club", age:"Ages 6+", permissions:["Offline first","No account","No ads"], icon:"అ", accent:"#e34a7a" },
  { id:"eco-patrol", name:"Eco Patrol", teluguName:"ఎకో పెట్రోల్", tagline:"Tiny missions for a cleaner, greener village.", description:"Complete practical nature missions, learn about waste and water, and build planet-friendly habits without sharing personal information.", category:"Games", version:"Concept", size:"Coming soon", android:"Android 8+ planned", updated:"Concept stage", maker:"KGM Green Team", age:"Ages 7+", permissions:["No camera","No location","No ads"], icon:"✦", accent:"#2c9b55" },
  { id:"study-buddy", name:"Study Buddy", teluguName:"స్టడీ బడ్డీ", tagline:"A calm homework and revision companion.", description:"Create simple study sessions, use focus timers and keep revision goals on the device. No sign-in and no cloud profile required.", category:"Tools", version:"Concept", size:"Coming soon", android:"Android 8+ planned", updated:"Concept stage", maker:"KGM Young Coders", age:"Ages 10+", permissions:["Local data only","No account","No ads"], icon:"✓", accent:"#2878d1" },
];

const tracks: Track[] = [
  { id:"bujji-meka", title:"Bujji Meka Bujji Meka", teluguTitle:"బుజ్జి మేక బుజ్జి మేక", artist:"Indic Oral Culture Project", language:"Telugu", mood:"Children · Telugu folk", duration:"0:21", license:"CC0 1.0", sourceUrl:"https://commons.wikimedia.org/wiki/File:బుజ్జి_మేక_బుజ్జి_మేక.webm", audioUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/బుజ్జి_మేక_బుజ్జి_మేక.webm", note:"A short Telugu children’s folk recording released into CC0.", icon:"మే" },
  { id:"randi-papalu", title:"Randi Randi Papalu", teluguTitle:"రండి రండి పాపలు", artist:"Indic Oral Culture Project", language:"Telugu", mood:"Children · Telugu rhyme", duration:"0:31", license:"CC0 1.0", sourceUrl:"https://commons.wikimedia.org/wiki/File:రండి_రండి_పాపలు.webm", audioUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/రండి_రండి_పాపలు.webm", note:"A Telugu children’s rhyme released into CC0.", icon:"రా" },
  { id:"greensleeves", title:"Greensleeves", artist:"Traditional", language:"English / Folk", mood:"Traditional English folk", duration:"0:36", license:"Public Domain", sourceUrl:"https://commons.wikimedia.org/wiki/File:Greensleaves.ogg", audioUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Greensleaves.ogg", note:"A public-domain performance of the traditional English melody.", icon:"♪" },
  { id:"shall-not-move", title:"I Shall Not Be Moved", artist:"Gid Tanner · traditional", language:"English / Folk", mood:"Traditional · archival folk", duration:"3:06", license:"Public Domain", sourceUrl:"https://commons.wikimedia.org/wiki/File:IShallNotBeMoved.ogg", audioUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/IShallNotBeMoved.ogg", note:"A historic traditional performance available in the public domain.", icon:"♬" },
];

const categories: Category[] = ["All","Learning","Games","Village","Tools"];
const musicLanguages: MusicLanguage[] = ["All","Telugu","English / Folk","My uploads"];
const DB_NAME="kgm-music-library", STORE_NAME="songs";

function openSongDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE_NAME))db.createObjectStore(STORE_NAME,{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function readStoredSongs():Promise<StoredSong[]>{const db=await openSongDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE_NAME,"readonly").objectStore(STORE_NAME).getAll();req.onsuccess=()=>resolve((req.result as StoredSong[]).sort((a,b)=>b.createdAt-a.createdAt));req.onerror=()=>reject(req.error);});}
async function saveStoredSong(song:StoredSong){const db=await openSongDb();await new Promise<void>((resolve,reject)=>{const req=db.transaction(STORE_NAME,"readwrite").objectStore(STORE_NAME).put(song);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error);});}
async function removeStoredSong(id:string){const db=await openSongDb();await new Promise<void>((resolve,reject)=>{const req=db.transaction(STORE_NAME,"readwrite").objectStore(STORE_NAME).delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error);});}

function Icon({name,size=20}:{name:"search"|"shield"|"download"|"arrow"|"close"|"check"|"menu"|"github"|"spark"|"music"|"play"|"pause"|"upload"|"trash";size?:number}){
  const paths={search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,shield:<><path d="M12 3 5 6v5c0 4.6 2.7 8 7 10 4.3-2 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></>,download:<><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></>,arrow:<><path d="M5 12h14"/><path d="m14 7 5 5-5 5"/></>,close:<><path d="m6 6 12 12"/><path d="M18 6 6 18"/></>,check:<path d="m5 12 4 4L19 6"/>,menu:<><path d="M4 7h16"/><path d="M4 12h16"/><path d="M4 17h16"/></>,github:<><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7.4A5.8 5.8 0 0 0 19.3 3 5.4 5.4 0 0 0 19.1 0S17.9-.4 15 1.6a13.4 13.4 0 0 0-7 0C5.1-.4 3.9 0 3.9 0a5.4 5.4 0 0 0-.2 3A5.8 5.8 0 0 0 2.2 7.1c0 5.8 3.5 7 6.8 7.4A4.8 4.8 0 0 0 8 18v4"/><path d="M8 19c-3 .9-3-1.5-4.2-2"/></>,spark:<><path d="m12 3 1.2 3.8L17 8l-3.8 1.2L12 13l-1.2-3.8L7 8l3.8-1.2L12 3Z"/></>,music:<><path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/></>,play:<path d="m8 5 11 7-11 7V5Z"/>,pause:<><path d="M9 5v14"/><path d="M15 5v14"/></>,upload:<><path d="M12 16V4"/><path d="m7 9 5-5 5 5"/><path d="M5 20h14"/></>,trash:<><path d="M4 7h16"/><path d="M9 7V4h6v3"/><path d="m7 7 1 14h8l1-14"/></>};
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

export default function Home(){
  const [query,setQuery]=useState(""); const [category,setCategory]=useState<Category>("All"); const [selected,setSelected]=useState<AppEntry|null>(null); const [menuOpen,setMenuOpen]=useState(false); const [telugu,setTelugu]=useState(false); const [musicLanguage,setMusicLanguage]=useState<MusicLanguage>("All"); const [uploadedSongs,setUploadedSongs]=useState<StoredSong[]>([]); const [activeTrack,setActiveTrack]=useState<Track|null>(null); const [isPlaying,setIsPlaying]=useState(false); const [uploadOpen,setUploadOpen]=useState(false); const [uploadMessage,setUploadMessage]=useState(""); const audioRef=useRef<HTMLAudioElement>(null);

  const filteredApps=useMemo(()=>{const needle=query.trim().toLowerCase();return apps.filter(app=>(category==="All"||app.category===category)&&(!needle||[app.name,app.teluguName,app.tagline,app.maker,app.category].some(v=>v.toLowerCase().includes(needle))))},[category,query]);
  const uploadedTracks=useMemo<Track[]>(()=>uploadedSongs.map(song=>({id:song.id,title:song.title,artist:song.artist,language:song.language,mood:"KGM community upload",duration:"Local song",license:"Owned by uploader",audioUrl:URL.createObjectURL(song.blob),note:"Stored privately in this browser and played inside KGM.",icon:"K",uploaded:true})),[uploadedSongs]);
  const allTracks=useMemo(()=>[...uploadedTracks,...tracks],[uploadedTracks]);
  const filteredTracks=useMemo(()=>allTracks.filter(track=>musicLanguage==="All"||(musicLanguage==="My uploads"?track.uploaded:track.language===musicLanguage)),[allTracks,musicLanguage]);

  useEffect(()=>()=>uploadedTracks.forEach(track=>URL.revokeObjectURL(track.audioUrl)),[uploadedTracks]);
  useEffect(()=>{readStoredSongs().then(setUploadedSongs).catch(()=>setUploadMessage("Local music storage is unavailable in this browser."));},[]);
  useEffect(()=>{document.body.style.overflow=selected?"hidden":"";const onKeyDown=(event:KeyboardEvent)=>event.key==="Escape"&&setSelected(null);window.addEventListener("keydown",onKeyDown);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",onKeyDown)}},[selected]);
  useEffect(()=>{if(activeTrack&&audioRef.current){audioRef.current.load();audioRef.current.play().then(()=>setIsPlaying(true)).catch(()=>setIsPlaying(false));}},[activeTrack]);

  function playTrack(track:Track){if(activeTrack?.id===track.id){if(audioRef.current?.paused)audioRef.current.play().catch(()=>setIsPlaying(false));else audioRef.current?.pause();return;}setActiveTrack(track);}

  async function handleUpload(event:FormEvent<HTMLFormElement>){event.preventDefault();setUploadMessage("");const form=event.currentTarget;const data=new FormData(form);const file=data.get("song") as File|null;const title=String(data.get("title")||"").trim();const artist=String(data.get("artist")||"").trim();const language=String(data.get("language")) as "Telugu"|"English / Folk";const owned=data.get("owned")==="on";if(!file||!file.size||!title||!artist||!owned){setUploadMessage("Add the audio, title and artist, then confirm you own it or have permission.");return;}if(file.size>25*1024*1024){setUploadMessage("Please keep each upload under 25 MB.");return;}if(!(file.type.startsWith("audio/")||file.type==="video/webm")){setUploadMessage("Use MP3, WAV, M4A, OGG or WebM audio.");return;}const song:StoredSong={id:`local-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,title,artist,language,fileName:file.name,mimeType:file.type,blob:file,createdAt:Date.now()};try{await saveStoredSong(song);setUploadedSongs(prev=>[song,...prev]);form.reset();setUploadMessage("Added to My uploads. It now plays inside KGM on this device.");setMusicLanguage("My uploads");}catch{setUploadMessage("Could not save this file locally. Check browser storage permissions.");}}
  async function deleteUpload(track:Track){await removeStoredSong(track.id);setUploadedSongs(prev=>prev.filter(song=>song.id!==track.id));if(activeTrack?.id===track.id){audioRef.current?.pause();setActiveTrack(null);setIsPlaying(false);}}

  return <main className={activeTrack?"has-music-player":""}>
    <header className="site-header"><a className="brand" href="#top" aria-label="Koratlagudem APK Hub home"><span className="brand-mark"><span>K</span></span><span><strong>KGM</strong><small>APK HUB</small></span></a><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Icon name="menu"/></button><nav className={menuOpen?"nav-links open":"nav-links"}><a href="#apps" onClick={()=>setMenuOpen(false)}>Explore apps</a><a href="#music" onClick={()=>setMenuOpen(false)}>Music</a><a href="#install" onClick={()=>setMenuOpen(false)}>Install Android</a><PwaInstallButton onInteraction={()=>setMenuOpen(false)}/><a href="#safety" onClick={()=>setMenuOpen(false)}>Safety</a><a href="#build" onClick={()=>setMenuOpen(false)}>Young creators</a><button className="language-button" onClick={()=>setTelugu(!telugu)}>{telugu?"English":"తెలుగు"}</button></nav></header>

    <section className="hero" id="top"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-content"><div className="eyebrow"><span className="live-dot"/> Built in Koratlagudem · Shared with everyone</div><h1>{telugu?<><span>మన ఊరి పిల్లలు.</span><br/><em>మన యాప్స్.</em> ప్రపంచం కోసం.</>:<>Small village.<br/><em>Big ideas.</em> Apps for everyone.</>}</h1><p>{telugu?"కోరట్లగూడెం యువ సృష్టికర్తలు రూపొందించిన సురక్షితమైన, ఉపయోగకరమైన ఆండ్రాయిడ్ యాప్స్‌కు మన కమ్యూనిటీ హోమ్.":"The community home for safe, useful Android apps imagined and built by the young creators of Koratlagudem."}</p><div className="hero-actions"><a className="primary-button" href="#apps">Explore the apps <Icon name="arrow"/></a><a className="text-button" href="#music">Play KGM music <span>♫</span></a></div><div className="trust-strip"><span><Icon name="shield" size={18}/> Mentor-reviewed releases</span><span><Icon name="check" size={18}/> Clear permissions</span><span><Icon name="music" size={18}/> Music plays here</span></div></div><div className="hero-visual"><div className="phone-shell"><div className="phone-top"><span>9:41</span><i/></div><div className="phone-greeting"><small>నమస్కారం 👋</small><strong>What will you discover?</strong></div><div className="mini-search"><Icon name="search" size={16}/> Search KGM apps</div><div className="mini-featured"><span className="mini-app-icon" style={{background:apps[1].accent}}>{apps[1].icon}</span><div><small>FEATURED</small><strong>{apps[1].name}</strong><p>{apps[1].tagline}</p></div></div><div className="mini-grid">{apps.slice(0,4).map(app=><div key={app.id}><span style={{background:app.accent}}>{app.icon}</span><small>{app.name}</small></div>)}</div><div className="phone-home"/></div><div className="floating-note note-one"><span>6</span><small>ideas growing</small></div><div className="floating-note note-two"><Icon name="music"/><small>KGM Folk Radio</small></div></div></section>

    <section className="story-band"><div><span className="story-number">01</span><p><strong>Imagine</strong><br/>A child spots a problem worth solving.</p></div><div><span className="story-number">02</span><p><strong>Build</strong><br/>They turn curiosity into working code.</p></div><div><span className="story-number">03</span><p><strong>Share</strong><br/>A safe release reaches the community.</p></div></section>

    <section className="apps-section" id="apps"><div className="section-heading"><div><span className="section-kicker">THE COMMUNITY SHELF</span><h2>{telugu?"కోరట్లగూడెంలో తయారు చేయబడింది":"Made in Koratlagudem"}</h2><p>Fresh ideas from young builders. Published apps will include a verified APK, version details and a safety note.</p></div><div className="catalog-count"><strong>{apps.length}</strong><span>ideas<br/>growing</span></div></div><div className="catalog-tools"><label className="search-box"><Icon name="search"/><span className="sr-only">Search apps</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search apps, creators or categories…"/></label><div className="category-list">{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div></div><div className="app-grid">{filteredApps.map((app,index)=><article className={app.featured?"app-card featured":"app-card"} key={app.id}><div className="card-topline"><span>{app.category}</span><small>{String(index+1).padStart(2,"0")}</small></div><button className="card-main" onClick={()=>setSelected(app)}><span className="app-icon" style={{background:app.accent}}>{app.icon}</span><span className="app-copy"><strong>{app.name}</strong><em>{app.teluguName}</em><p>{app.tagline}</p></span></button><div className="card-meta"><span>{app.age}</span><span>•</span><span>{app.maker}</span></div><div className="card-actions"><button className="details-button" onClick={()=>setSelected(app)}>View details <Icon name="arrow" size={17}/></button><span className="status-pill">In the lab</span></div></article>)}</div></section>

    <section className="music-section" id="music"><div className="music-hero"><div><span className="section-kicker light">KGM FOLK RADIO · గ్రామ స్వరాలు</span><h2>{telugu?<>యాప్స్ చూస్తూ<br/><em>సంగీతం వినండి.</em></>:<>Stay in KGM.<br/><em>Let the village play.</em></>}</h2><p>{telugu?"పాట కోసం మరో వెబ్‌సైట్‌కి వెళ్లాల్సిన అవసరం లేదు. ఇక్కడే వినండి, మీ పాటలను కూడా జోడించండి.":"Songs now play directly inside KGM. Add your own village recordings too, and keep browsing while the music continues."}</p><div className="music-badges"><span>✓ In-app audio player</span><span>✓ Telugu + English folk</span><span>✓ Your own uploads</span></div></div><div className="radio-orb"><Icon name="music" size={46}/><span className="wave w1"/><span className="wave w2"/><span className="wave w3"/><small>KGM<br/>RADIO</small></div></div>
      <div className="music-toolbar"><div className="music-tabs">{musicLanguages.map(item=><button key={item} className={musicLanguage===item?"active":""} onClick={()=>setMusicLanguage(item)}>{item}</button>)}</div><button className="upload-song-button" onClick={()=>setUploadOpen(v=>!v)}><Icon name="upload" size={17}/>{uploadOpen?"Close uploader":"Add your song"}</button></div>
      {uploadOpen&&<form className="song-upload-panel" onSubmit={handleUpload}><div className="upload-copy"><span className="section-kicker">YOUR MUSIC · మీ పాటలు</span><h3>Add a song to KGM</h3><p>This version stores the audio on this browser/device using IndexedDB, so it stays private and plays inside KGM. For a song that everyone should hear, add the approved audio file to the repo’s <code>public/music</code> folder later.</p></div><div className="upload-fields"><label>Song title<input name="title" required placeholder="e.g. Mana Ooru Janapadam"/></label><label>Artist / singer<input name="artist" required placeholder="Name or KGM Music Club"/></label><label>Language<select name="language" defaultValue="Telugu"><option>Telugu</option><option>English / Folk</option></select></label><label className="audio-drop">Audio file<input name="song" type="file" required accept="audio/*,.mp3,.wav,.m4a,.ogg,.webm"/><span>MP3 · WAV · M4A · OGG · WebM · max 25 MB</span></label><label className="ownership-check"><input name="owned" type="checkbox" required/> I own this recording or have permission to use it.</label><button type="submit" className="save-song-button"><Icon name="upload"/> Add to KGM</button>{uploadMessage&&<p className="upload-message">{uploadMessage}</p>}</div></form>}
      <div className="track-grid">{filteredTracks.map(track=><article className={activeTrack?.id===track.id?"track-card playing":"track-card"} key={track.id}><div className="track-art"><span>{track.icon}</span><i/></div><div className="track-copy"><div className="track-kicker"><span>{track.uploaded?"My upload":track.language}</span><b>{track.duration}</b></div><h3>{track.title}</h3>{track.teluguTitle&&<em>{track.teluguTitle}</em>}<p>{track.artist} · {track.mood}</p><small>{track.note}</small><div className="track-actions"><button className="play-source" onClick={()=>playTrack(track)}>{activeTrack?.id===track.id&&isPlaying?<><Icon name="pause" size={16}/> Pause</>:<><Icon name="play" size={16}/> Play in KGM</>}</button><span className="license-pill">{track.license}</span>{track.uploaded?<button className="delete-track" onClick={()=>deleteUpload(track)} title="Remove upload"><Icon name="trash" size={15}/></button>:track.sourceUrl&&<a className="source-credit" href={track.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a>}</div></div></article>)}</div>
      {musicLanguage==="My uploads"&&!uploadedTracks.length&&<div className="music-empty"><Icon name="music" size={30}/><h3>Your KGM music shelf is empty</h3><p>Use “Add your song” to bring in your own village recording.</p></div>}
      <div className="music-note"><Icon name="shield"/><p><strong>Two safe music paths.</strong> Personal uploads remain on the current browser/device. Curated public tracks stream through KGM’s player from sources with clear reuse terms; the source remains visible for attribution.</p></div>
    </section>

    <section className="safety-section" id="safety"><div className="safety-copy"><span className="section-kicker light">BEFORE ANY “INSTALL”</span><h2>Trust is a feature.<br/>We build it in.</h2><p>Community software should be easy to understand—not a mystery box. Each published APK must pass a simple, visible review before its download button goes live.</p><a href="https://github.com/UpendarRaoGunda/kgm-playstore" target="_blank" rel="noreferrer">See the open-source project <Icon name="arrow" size={17}/></a></div><div className="safety-grid">{[["01","Malware scan","Every release file is scanned before publishing."],["02","Permission check","Camera, location and storage access must be justified."],["03","Mentor review","An adult reviewer checks content and privacy."],["04","Version history","Creator, version and update notes stay visible."]].map(([number,title,copy])=><div className="safety-item" key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section>
    <AndroidInstall />
    <section className="builder-section" id="build"><div className="builder-label">FOR KORATLAGUDEM’S<br/>NEXT GENERATION</div><div className="builder-main"><span className="section-kicker light">YOUNG CREATOR? START HERE.</span><h2>Your first app does not need to be perfect.<br/><em>It needs to be yours.</em></h2><p>Bring a useful idea, a working Android build and what you learned. A mentor can help check privacy, permissions and the release details before it joins the community shelf.</p><div className="builder-actions"><a className="light-button" href="https://github.com/UpendarRaoGunda/kgm-playstore/issues/new?template=app-submission.yml" target="_blank" rel="noreferrer">Submit an app <Icon name="arrow"/></a><a href="https://github.com/UpendarRaoGunda/kgm-playstore" target="_blank" rel="noreferrer"><Icon name="github"/> View the project</a></div></div></section>
    <footer><a className="brand footer-brand" href="#top"><span className="brand-mark"><span>K</span></span><span><strong>KGM</strong><small>APK HUB</small></span></a><p>Made with curiosity in Koratlagudem, Telangana.<br/><span>మన ఊరు · మన కోడ్ · మన స్వరాలు · మన భవిష్యత్తు</span></p><div><a href="#apps">Apps</a><a href="#music">Music</a><a href="#safety">Safety</a><a href="#build">Submit</a></div></footer>

    {activeTrack&&<div className="music-player" role="region" aria-label="KGM music player"><audio ref={audioRef} src={activeTrack.audioUrl} preload="metadata" onPlay={()=>setIsPlaying(true)} onPause={()=>setIsPlaying(false)} onEnded={()=>setIsPlaying(false)} controls/><div className="player-track"><span>{activeTrack.icon}</span><div><small>NOW PLAYING IN KGM</small><strong>{activeTrack.title}</strong><em>{activeTrack.artist}</em></div></div><button className="player-close" onClick={()=>{audioRef.current?.pause();setActiveTrack(null);setIsPlaying(false)}} aria-label="Close player"><Icon name="close"/></button></div>}

    {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="app-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setSelected(null)}><Icon name="close"/></button><div className="modal-hero" style={{background:selected.accent}}><span className="modal-icon">{selected.icon}</span><small>{selected.category} · {selected.age}</small></div><div className="modal-body"><span className="status-pill">Preview listing</span><h2>{selected.name}</h2><em>{selected.teluguName}</em><p>{selected.description}</p><div className="modal-facts"><div><small>VERSION</small><strong>{selected.version}</strong></div><div><small>SIZE</small><strong>{selected.size}</strong></div><div><small>REQUIRES</small><strong>{selected.android}</strong></div></div><h3>Privacy at a glance</h3><div className="permission-list">{selected.permissions.map(permission=><span key={permission}><Icon name="check" size={15}/>{permission}</span>)}</div><div className="creator-line"><span>Created by</span><strong>{selected.maker}</strong><small>{selected.updated}</small></div>{selected.apkUrl?<a className="modal-install" href={selected.apkUrl} download><Icon name="download"/> Download APK</a>:<button className="modal-install disabled" disabled>APK coming after safety review</button>}<p className="modal-note">This is a transparent preview listing—not a published APK.</p></div></section></div>}
  </main>;
}
